### ISSUE TITLE
Nginx base image should auto-set nested folder permissions

### ISSUE THREAD

**Issue by M0ter** [exoframejs/exoframe#100]
I have tried deploying a static website with the nginx docker image.

I have a problem where i can only serve files from the root directory.

So for example, if i have index.html in the root dir and a dir `/css` with css in it and a folder `/js` with js in it.
I will get a 403 error trying to access the files in `/css` and `/js`.

**Comment by yamalight** [comment]
@M0ter that's a way nginx base image is made. I'll add a workaround for it in the nearest future 🤔 
For now you can fix it either by `chmod 777` on your folders, or you can create custom Dockerfile that'd look something like:
```
FROM nginx:latest
COPY . /usr/share/nginx/html
RUN chmod -R 777 /usr/share/nginx/html
```

**Comment by yamalight** [comment]
Done and ready for release in 2.0
