### ISSUE TITLE
Questions about design and architecture

### ISSUE THREAD

**Issue by FWeinb** [exoframejs/exoframe#101]
I have some questions about the design of exoframe and exoframe-server. As it is now the server will analyse the project and chooses a template to run the project. The server can also just run a Dockerfile and you are basically free to do anything in there. 

Wouldn't it be better if the exoframe-cli could choose the template, write a custom Dockerfile and the server would just run that. I am obviously missing something here but I think that pulling as much logic from the server into the client would allow for a more stable server and less frequent updates for the server software. 

The only caveat with that approach is that updating the exoframe-cli can result in different builds. To improve this situation the server should reject a deployment from an outdated client (unless e.g. `--force` was used)

Just thinking out loud here as I said I could have overlooked something basic.

**Comment by yamalight** [comment]
Choosing templates is going to be added in 2.0, you can see related issue here: https://github.com/exoframejs/exoframe/issues/79

As for moving that part to client - I think it's better to leave it on server, that gives more control over what kind of apps can be deployed to administrators. Also incompatibility bit is quite annoying, yes.

Going to close this, feel free to reopen if you want to clarify something.

**Comment by FWeinb** [comment]
I can understand that having control of what gets deployed on the server is good for administration but as of now a user is free to just use a Dockerfile to deploy whatever he likes, will that change after #79? Are you planning some administrator configuration on what templates are allowed on a server?

**Comment by yamalight** [comment]
Yep, in a long run that's a planned addition. #79 just prepares base for it

**Comment by yamalight** [comment]
Probably should make a ticket and a roadmap for that 🤔

**Comment by FWeinb** [comment]
Thanks for the explanation. Looking forward to it!

**Comment by yamalight** [comment]
Added basic outline in #102
