### ISSUE TITLE
Allow use with existing traefik container

### ISSUE THREAD

**Issue by airtonix** [exoframejs/exoframe#103]
I already use Traefik in our coreos server to handle load balancing other services, I'm not keen on taking it down.

Ideally I'd like to use Exoframe in a container and let my existing Traefik handle the rules.

**Comment by yamalight** [comment]
That sounds doable.
Basically exoframe-server would need a new config entries for traefik container name and traefik network 🤔

**Comment by yamalight** [comment]
This is now possible in `develop` branch by setting `traefikImage: false` in server config.
Closing the issue.
