### ISSUE TITLE
Node Env Variable Support?

### ISSUE THREAD

**Issue by emveeoh** [exoframejs/exoframe#110]
I did a quick docs scan and didn't see any support for environment variables. If they are supported, do they persist with each new deployment?

**Comment by yamalight** [comment]
@emveeoh you can use exoframe config to set env vars for your project. either via cli by running `exoframe config` or manually editing `exoframe.json`. 
You can find config description here in the docs: https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#project-config-file
