### ISSUE TITLE
Allow setting baseDomain without leading dot

### ISSUE THREAD

**Issue by benmerckx** [exoframejs/exoframe#111]
Setting a basedomain in `server.config.yml` like this:
````
baseDomain: example.com
````
Results in deploys getting urls like this: `exo-deploy-public-8633eac0example.com` (not a subdomain)
Not sure if it's expected that the domain is set with leading dot (eg `.example.com`) but it's not mentioned in the docs currently.

**Comment by yamalight** [comment]
@benmerckx thanks for reporting. This is a valid point and definitely should be addressed.
I'll add a check for leading `.` and pre-pend it if it's not there. Will also clarify that in the docs.

**Comment by yamalight** [comment]
Done in [exoframe-server 2.0.2](https://github.com/exoframejs/exoframe-server/releases/tag/2.0.2)
