### ISSUE TITLE
Unique deploys seem to be load balanced

### ISSUE THREAD

**Issue by benmerckx** [exoframejs/exoframe#113]
As I hinted at in #112 it seems multiple deploys of the same project (without a domain set or using `-u`) seem to be load balanced instead of being tied to their unique url. I set up a simple node webserver to print a different string on each deploy. After 3 deploys each of the urls get load balanced across all of the  3 containers. This also happens with docker deploys for me.

You can follow what happens here (sorry it's 1.2MB):

![exotest](https://user-images.githubusercontent.com/10584189/35433921-76cfd2e8-0285-11e8-80e7-d0a31e0a153e.gif)

**Comment by yamalight** [comment]
@benmerckx nice catch! that's definitely not intended.
Will try to push a patch fixing that today.

**Comment by yamalight** [comment]
Fixed in [exoframe-server 2.0.2](https://github.com/exoframejs/exoframe-server/releases/tag/2.0.2)
