### ISSUE TITLE
Use with different domain

### ISSUE THREAD

**Issue by vihanb** [exoframejs/exoframe#114]
I am attempting to run exoframe behind a reverse proxy at `foo.example.com`. This means that rather than running at `0.0.0.0`, exoframe should run at `foo.example.com` I tried to change this in `src/index.js` however when rebuilding exoframe-server, and then running the docker command:

```
docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /home/me/exoframe-server \
  -v /home/me/.ssh/authorized_keys \
  -e EXO_PRIVATE_KEY=myprivatekey \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:foo.example.com \
  --name exoframe-server \
  exoframe/server
```

Logs show:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint exoframe-traefik (8673647336a28cb0e250ef51144b5e3286147fdf4d12ef2042057551e4ab7a6e): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
```

It also seems like the docker is correctly build and the exoframe-server binary has the correct domain in it

**Comment by yamalight** [comment]
@vihanb exoframe-server starts correctly, but fails to start traefik. 
looks like port 443 is already taken on your machine by something - that's why traefik fails to start

**Comment by yamalight** [comment]
going to close this. feel free to re-open if there are still issues.
