### ISSUE TITLE
Simpler endpoint switching using login command

### ISSUE THREAD

**Issue by tonyrewin** [exoframejs/exoframe#115]
> Make sure you have Exoframe server deployed, set it as your endpoint using:
> 
> exoframe endpoint http://you.server.url
> Then login using:
> 
> exoframe login

whould be so pleasant to shorten as 
`exoframe login endpoint.yourserver.url`

**Comment by yamalight** [comment]
@tonyrewin that's a pretty nice suggestion! will be happy to accept a PR (or will add it at some point myself)
