### ISSUE TITLE
Deployment of docker-compose results in "Gateway timeout"

### ISSUE THREAD

**Issue by FWeinb** [exoframejs/exoframe#116]
When I try to `exoframe --update` a docker-compose project I get "Gateway timeout". If I add the label `traefik.docker.network: 'exoframe'` to the service that exports the web frontend everything is working fine.

**Comment by yamalight** [comment]
Can you please try to run deployment in verbose mode (`exoframe -vvv --update`) and check the logs?

**Comment by FWeinb** [comment]
Made a gist [here](https://gist.github.com/FWeinb/ea730fef2829d78bd81c358fa17d2ad6).

**Comment by yamalight** [comment]
@FWeinb seems like it was successful?

**Comment by FWeinb** [comment]
Yeah It will give me back a success but accessing the deployed app will result in an "Gateway timeout"

**Comment by yamalight** [comment]
Ah, now I get the issue. Yes, looks like due to your docker config you need to specify the network for traefik explicitly.

**Comment by FWeinb** [comment]
Okay. I setup exoframe-server like this:
```
sudo docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /root/exoframe:/root/.exoframe \
  -v /root/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
  -e EXO_PRIVATE_KEY=********* \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:dev.weinberg.me \
  --name exoframe-server \
  exoframe/server:latest
```

and server.config.yml:
```
debug: false
letsencrypt: true
letsencryptEmail: ***********
compress: true
baseDomain: dev.weinberg.me
cors: false
updateChannel: stable
traefikImage: 'traefik:latest'
traefikName: exoframe-traefik
traefikArgs: []
exoframeNetwork: exoframe
publicKeysPath: /root/.ssh
```

**Comment by yamalight** [comment]
the thing is - exoframe doesn't control docker-compose deployments completely (as it's mentioned in the docs), so you'll have to provide the traefik config yourself. that is why you need those additional labels.

**Comment by FWeinb** [comment]
Thanks for clarifying.

**Comment by yamalight** [comment]
Going to close this, feel free to re-open if something's still unclear
