### ISSUE TITLE
Exoframe deploy always deploys new container

### ISSUE THREAD

**Issue by bkniffler** [exoframejs/exoframe#124]
Using exoframe.json
```
{
  "name": "xyz",
  "restart": "on-failure:2",
  "env": { "PORT": 80 },
  "domain": "api-dev.xyz.xyz"
}
```

And deploying twice
```
Your project is now deployed as:

   ID                                 URL                     Hostname
   exo-bkniffler-xyz-59748e30       api-dev.xyz.xyz       Not set
SnackBook:api bkniffler$ exoframe deploy
Deploying current project to endpoint: https://exo.xyz.xyz
✔ Upload finsihed!
Your project is now deployed as:

   ID                                 URL                     Hostname
   exo-bkniffler-xyz-5fa9e930       api-dev.xyz.xyz       Not set
SnackBook:api bkniffler$ exoframe ls
2 deployments found on https://exo.xyz.xyz:

Deployments for exo-bkniffler-diego:

   ID                                 URL                     Hostname       Status
   exo-bkniffler-xyz-5fa9e930       api-dev.xyz.xyz       Not set        running
   exo-bkniffler-xyz-59748e30       api-dev.xyz.xyz       Not set        running

SnackBook:api bkniffler$
```

So, shouldn't exoframe put the old one to sleep if you deploy a new one with the exact same url/domain? It makes sense if you do not assign a specific url and if you use the auto generated one.

**Comment by yamalight** [comment]
This is very much intended.
If you want to replace old instance, you need to use `exoframe -u` flag.
See this [section on updates in docs](https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#updating-deployed-project) for more details.

**Comment by bkniffler** [comment]
Hey, I totally get why it makes sense if you autogenerate, since its exactly how zeit now also works. But does it really make sense to deploy multiple containers that are bound to the exact same url? 

But thanks for pointing me to -u flag, missed this part of the docs. Works good!

Oh, and thanks for exoframe, I'm really pleased by how much flexibility it gives me, and how simple it is to setup and use!

**Comment by yamalight** [comment]
Thanks! Really happy to hear you found it simple to use yet flexible 😄 

Deploying multiple containers to exact URL allows you to balance requests between those containers (traefik does that automatically). That might be useful for multiple thing. And will get even more useful once Swarm support is released in Exoframe v3.0 😃

**Comment by bkniffler** [comment]
Oh, I'm not very firm with traefik, but that explains some issue I was having with my API returning different responses!

Thats actually pretty cool for load balancing and to scale my app. I'm eager to know how swarm support would improve this further?

Would it maybe make sense to introduce a deploy argument (`exoframe deploy -i 3` to deploy 3 instances/containers and `exoframe deploy -i 3 -u` to replace any previous containers with 3 new ones)?

**Comment by yamalight** [comment]
Swarm support would allow you to scale your app over multiple servers - I'd say that would be the primary improvement 😃 

Scaling via CLI is on the roadmap, but I haven't had time to add an issue for it yet. Your suggestion looks pretty nice actually, will write it down to a ticket now. Thanks! 👍
