### ISSUE TITLE
Support for zero downtime deployment

### ISSUE THREAD

**Issue by haroldtrialx** [exoframejs/exoframe#126]
Right now its only supporting near zero downtime. It would be great if we could support this.

**Comment by yamalight** [comment]
that's a good point, thanks for bringing it up.
I've already added support for zero-downtime deployments when running in swarm mode. 
makes sense to also bring it to non-swarm mode.

**Comment by yamalight** [comment]
Partially done in: https://github.com/exoframejs/exoframe-server/commit/e0e3e520ef0c5d1738529e271567f4fb98e39692

Partially blocked due to a few minor traefik bugs. Closing as it's now up to traefik fixes.
