### ISSUE TITLE
Error when deploying to an Exoframe instance with docker network name other than exoframe

### ISSUE THREAD

**Issue by henrikcoll** [exoframejs/exoframe#127]
When I try to deploy to an Exoframe instance that uses "traefik" as docker network instead of "exoframe" I get TypeError: Cannot read property 'Aliases' of undefined.

I think the issue is on line 7 and 8 in [formatServices.js](https://github.com/exoframejs/exoframe/blob/master/src/util/formatServices.js).

**Comment by yamalight** [comment]
Can you please describe steps to reproduce this bug?

**Comment by yamalight** [comment]
ahh, never mind, I see why it happens now! will release a hotfix tomorrow. thanks for reporting! 👍

**Comment by yamalight** [comment]
@henrikcoll should be fixed in 2.1.1
Please let me know if that works

**Comment by henrikcoll** [comment]
It works 😃

**Comment by yamalight** [comment]
great, thanks for getting back 😃
