### ISSUE TITLE
Additional Logging Features

### ISSUE THREAD

**Issue by acupajoe** [exoframejs/exoframe#129]
Thanks so much for the work you've done on this project, am enjoying being able to do deploys like this. 

I think it'd be a great feature to have the `log` function (1) default to the last deployed container and (2) to add a `-t` or `--tail` flag(s) to stream logs as they come in. I know several other systems allow you to do that (firebase, dokku, etc). Although, looking through the code, it looks like you're just making an http request for the logs, so it would require some significant changes AFAIK.

Thoughts?

**Comment by yamalight** [comment]
Hey @acupajoe! 
That should be relatively easy to do. I'll implement it once I have time (or PRs welcome) :)
