### ISSUE TITLE
I'm a noob, how do I login?

### ISSUE THREAD

**Issue by robgraeber** [exoframejs/exoframe#131]
Hi I'm having issues getting exoframe to login. What I have is an aws instance I installed docker on, then ran:
```
sudo docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /home/ubuntu/.exoframe:/root/.exoframe \
  -v /home/ubuntu/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
  -e EXO_PRIVATE_KEY=asdf \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:ec2-18-208-62-43.compute-1.amazonaws.com \
  --name exoframe-server \
  exoframe/server
``` 

Then I do `exoframe login` with the pem key and no passphrase, which I use to ssh into the server. But getting connection refused errors:
```
exoframe login                                                                                                                                            
Logging in to: ec2-18-208-62-43.compute-1.amazonaws.com
? Username: ubuntu
? Private key: MyKey.pem
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error getting login request phrase. Make sure your endpoint is correct! RequestError: connect ECONNREFUSED 18.208.62.43:443
```

Where 18.208.62.43 is the ip of ec2-18-208-62-43.compute-1.amazonaws.com.
I made sure port 443 is open, but don't have a ssl cert of course.
 
When I go to ec2-18-208-62-43.compute-1.amazonaws.com, it shows the exoframe landing page.

Any idea for what else I can try?

**Comment by robgraeber** [comment]
I tried assigning setting up a real domain name with my aws instance via pointing the A Records at it's ip address, now I'm getting:

`Error logging in! Error getting login request phrase. Make sure your endpoint is correct! MaxRedirectsError: Redirected 10 times. Aborting.`

**Comment by yamalight** [comment]
@robgraeber have you set your endpoint to `ec2-18-208-62-43.compute-1.amazonaws.com`?
you can do that by using: `exoframe endpoint ec2-18-208-62-43.compute-1.amazonaws.com`
you should be able to login after that

**Comment by yamalight** [comment]
@robgraeber Oh, OK. Looks like it's an AWS problem - do you have port 80 and 443 permitted in your AWS security group?

**Comment by robgraeber** [comment]
@yamalight I got it working! After clearing my DNS cache with my custom domain. Not too sure why the aws dns url didn't work, maybe there should be a note that it needs a custom domain. 

A tip to anyone with similar issues, trying doing `curl your-exoframe-url.com/login` and verify it's returning some json.

**Comment by yamalight** [comment]
@robgraeber I have tried it with AWS domains (for upcoming release and [AWS swarm tutorial](https://github.com/exoframejs/exoframe/blob/develop/docs/TutorialSwarmAWS.md)) and it worked for me 🤔 but it definitely seems like AWS-related issue 
glad you resolved it though! 👍
