### ISSUE TITLE
Suggestions/Comments

### ISSUE THREAD

**Issue by robgraeber** [exoframejs/exoframe#134]
Hey man I was trying it out today and once I got it working I was pretty impressed. I think once you have swarm support out and maybe a more comprehensive faq/troubleshooting docs then Dokku is toast. If you're interested here's some issues/thoughts I had trying it:

* `baseDomain: false` in exoframe-server should default to the `traefik.frontend.rule=Host` label. I might be missing something but in most cases people will need a baseDomain set if they want it to work like your demo.
* Update flag (-u) is confusing. It's especially confusing if there's no domain set in exoframe.json. Since it will deploy a new temporary url then delete all other temporary url. How I expected it to work is to update a specified id with a new deploy.
* ~~Have a way for env variables to be set outside of exoframe.json. I want to avoid committing api keys to git and don't like so many settings coming from a file I'm going to gitignore.~~ This takes some getting use to, but I think this could be fine. Users would git ignore exoframe.json locally, then on a build server it would provide a exoframe.json with appropriate url + env variables.

**Comment by yamalight** [comment]
1. I think you misunderstand the purpose of `baseDomain`. If it's set to `false`, you have to manually assign domain name to each deployment using config file. If it's set to something (e.g. `baseDomain: .exoframe.com`) then all deployments that _don't_ have domain name explicitly set will get a subdomain under baseDomain (e.g. `my-project-ad1234.exoframe.com`)
2. Update flag works on project level, not domain level. There's a dedicated `project` property in config (generated from folder name by default)
3. I am currently trying to figure out a nicer way of handling secrets. Having them in a config is indeed not always desirable 😃

**Comment by robgraeber** [comment]
For baseDomain I think most people are going to want a base url set, it could be part of a quick start guide.

For the update flag, it makes sense when you have a domain set. But it's pretty confusing when you don't have one set. I wouldn't expect an update command to delete the rest of my project containers.

**Comment by yamalight** [comment]
1. I think you are overestimating a number of users who need that feature 😃  I feel the way it currently is described in the docs works OK. 

2. That's a tricky one actually, I couldn't figure out a better way but open to suggestions. One case is - how would you handle project updates done via e.g. compose file?

**Comment by robgraeber** [comment]
I’m guessing your envisioning people will mainly deploy to one url per project. While my plan is to use many temporary urls for development/testing, then have a job on my build server to deploy to the prod url. Since your demo video shows the multi url deployment, I think the setup instructions should be geared towards that. Not a big issue though.

For updating, I think it could be fine if the description is more explicit. Something like: ‘-u Update project with zero downtime and remove old containers’

**Comment by yamalight** [comment]
I'd be happy to accept a PRs with:
- an additional guide on multi-URL deployments
- explanation for the update flag

😄

**Comment by robgraeber** [comment]
Since the update flag swaps over the instances right after running npm start, urls could be dead for a while if there's a build task inside `npm start`. What do you think about supporting build and exo-build npm scripts that run before npm start like now.sh does?

**Comment by yamalight** [comment]
@robgraeber there's an issue open to fix downtime here: https://github.com/exoframejs/exoframe/issues/126 so it's in the works :)

**Comment by robgraeber** [comment]
Is multi template support also feasible? It’s a common use case to have a server written in one language then using node to build the frontend assets.

**Comment by yamalight** [comment]
Why not simply write your own Dockerfile in that case? 🤔

**Comment by robgraeber** [comment]
Biggest annoyances I had while troubleshooting builds: 
1. Often exoframe's deploy fail the first time with this error message:
```
[info] Deploying Dockerfile project..
[error] Build log contains errors!
Error deploying project: Error: Build log contains errors!
Build log:

No log available
```

Then I deploy it again without changing anything, and it works and deploys within 5 seconds.

2. While deploying, it doesn't show you the build log at all, even in verbose mode. I have to build the docker image locally to know what's going on.

3. I wish `exoframe logs` would accept container id's from any user. My jenkins/prod deploy job has it's own exoframe login and I can see the deployed container id it generates, but can't view the log without logging in as that user locally.

**Comment by yamalight** [comment]
1. That's a caveat/quirk of npm/yarn - sometimes during builds npm/yarn will display errors, but install will not fail (so, exit code is still 0). That leads to container being assembled, but the app failing to start due to that error. I've tried to tackle it like this: 
https://github.com/exoframejs/exoframe-server/blob/master/src/docker/templates/node.js#L65 
But as you might notice, that approach is far from perfect. If you have any other better solutions in mind - would be more than happy to implement them!

2. It should display the build log if you run it with `-vvv` flag - does that not works correctly? If yes, please open a new issue!

3. That's a tricky one. In the long run I want to implement full [user management](https://github.com/exoframejs/exoframe/issues/102) with access control, etc. So just allowing everyone to read everything is not going to work. I guess that could be an "admin" feature as well 🤔

**Comment by robgraeber** [comment]
1. Hmm that's interesting my build was failing, but I had uploaded my local public folder so I didn't notice. This was for a dockerfile, so not too sure what can be done about that other than defaulting to verbose.
2. Yeah -vvv works, probably needs some docs for it. It's a little bit annoying because it seems to add a lot of new lines.
```
Step 4/7 : ADD . /app
 ---> 4dcb03acdd32
Step 5/7 : RUN sbt compile stage
 ---> Running in 3d5879d04523
Getting org.scala-sbt sbt 0.13.13 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.13!sbt.jar (1507ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (713ms)
``` 
Turns into:
```
[verbose] Step 4/7 : ADD . /app
[verbose] 

[verbose]  ---> 85c83a7e2e85

[verbose] Step 5/7 : RUN sbt compile stage
[verbose] 

[verbose]  ---> Running in ffbaea21ea77

[verbose] Getting org.scala-sbt sbt 0.13.13 ...
[verbose] 

[verbose] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.13/jars/sbt.jar ...
[verbose] 

[verbose] 	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.13!sbt.jar (397ms)
[verbose] 

[verbose] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
[verbose] 

[verbose] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (317ms)
[verbose] 
```

**Comment by robgraeber** [comment]
In this one docker build, it doesn't seem like there was any error but exoframe claimed there was. On the next rebuild it used the cached docker image and worked as expected. 🤔 

[BuildLog.txt.zip](https://github.com/exoframejs/exoframe/files/1912330/BuildLog.txt.zip)

**Comment by yamalight** [comment]
@robgraeber your build seem to actually fail:
```
[verbose] 
> chart-viewer@1.0.0 build /app
> gulp build
[verbose] sh: 1: 
[verbose] gulp: not found
```

**Comment by yamalight** [comment]
@robgraeber ok, I'm guessing it's because of the `http-errors` package. 
need to think about how to fix that 🤔 if you have any ideas - would be awesome

**Comment by robgraeber** [comment]
Is it worth trying to catch npm install errors? If there are issues while installing, I'd think either a build task or running the server would fail and exit with an error code.

**Comment by yamalight** [comment]
@robgraeber it's a valid question. I still feel like failing early is a better UX, but I'm no longer sure it's worth it due to erroneous fails 😑
gotta think about that..

**Comment by yamalight** [comment]
Opened a better-worded issue for this. Closing this one, if you have more things - feel free to open new issues :)
