### ISSUE TITLE
Docker-compose deploy not working

### ISSUE THREAD

**Issue by ludviglundgren** [exoframejs/exoframe#137]
Hi Tim!

Really nice project! I've deployed a couple of simple projects that works great, but when I'm trying to deploy a docker-compose project I can't get it to work and to expose port 80. It complains of 0.0.0.0:80 already being used. I've tried alot of things like different labels and passing networks but nothing seem work. Atleast not the combinations i've treid.

The example docker-compose project doesn't expose any ports, and then magically runs at 80/tcp in docker. But trying that doesn't seem to work for my test-api. My project does however work perfect locally at the exposed port 7770.

So my test-project you can find [here](https://github.com/ludviglundgren/exoframe-docker-compose)
A deploy log of my recent deploy done with `exoframe deploy -vvv` is [here](https://gist.github.com/ludviglundgren/3ca5ea412b133d4353642479ab984ca9).

My config for exoframe, in `server.config.yml` is

```
debug: false
letsencrypt: true
letsencryptEmail: email@mydomain.xyz
compress: true
baseDomain: false
cors: false
updateChannel: stable
traefikImage: 'traefik:latest'
traefikName: exoframe-traefik
traefikArgs: []
exoframeNetwork: exoframe
publicKeysPath: /root/.ssh
```
My startscript is 

```
        docker run -d \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v /home/admin/.exoframe:/root/.exoframe \
                -v /home/admin/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
                -e EXO_PRIVATE_KEY=mysecretkey \
                --label traefik.backend=exoframe-server \
                --label traefik.frontend.rule=Host:exoframe.mydomain.xyz \
                --name exoframe-server \
                  ##exoframe/server
```

I read some of the other issues related to docker-compose but didn't get any wiser.

Can you point me in the right direction maybe?

**Comment by yamalight** [comment]
Exoframe uses [traefik](https://traefik.io/) as a reverse proxy for managing access to deployed services.
You don't need to forward ports specifically, you just need to specify host label. 
Looking at your project - you already specify `traefik.frontend.rule: "Host:api-v1.lndgrn.xyz"`. That means your service will be available at `api-v1.lndgrn.xyz`

**Comment by yamalight** [comment]
traefik reads port from `EXPOSE` commaind in your dockerfile. you don't need to forward ports explicitly (so, those `ports` mappings can be removed from your docker-compose file)
