### ISSUE TITLE
Document using path rules for deployments

### ISSUE THREAD

**Issue by coderafei** [exoframejs/exoframe#138]
like https://zeit.co/docs/features/path-aliases
this very useful 😄

**Comment by yamalight** [comment]
@coderafei this is already possible, see [frontends](https://docs.traefik.io/basics/#frontends) part of the Traefik docs. Currently whatever you put into `exoframe.json` gets inserted as:
```js
containerConfig.Labels['traefik.frontend.rule'] = `Host:${config.domain}`;
```
So, if you want to add path, you can specify you domain like this: `my.domain.com;Path:/api`.

**Comment by samohovets** [comment]
Got it working by adding this to `domain` in exoframe.json:
```
"domain": "my.cloud.com;PathPrefixStrip:/api"
```
And app is working on my.cloud.com/api 😄

**Comment by yamalight** [comment]
I think we should be able to simplify this by using [URL](https://nodejs.org/dist/latest-v10.x/docs/api/url.html) parser and auto-splitting it into `${domain};PathPrefixString:${path}` 🤔

**Comment by yamalight** [comment]
After some digging I think it would be better to simply document it since Traefik provides a lot of ways of doing this 🤔
