### ISSUE TITLE
Requesting help with authentication of AWS swarm 

### ISSUE THREAD

**Issue by RegEM** [exoframejs/exoframe#141]
Hi. Kinda stuck,

I have the Tutorial Swarm running. Can login., ie. 'docker-machine ssh exo-master'. Currently getting splash screen at, http://ec2-52-206-230-3.compute-1.amazonaws.com/

I am stuck on establishing the authentication for 'exoframe login'.

I am on windows so mostly do commands in powershell. Maybe that's an issue.

Is the ' -e EXO_PRIVATE_KEY=your_private_key `' required?

I bypassed the following step. And am trying to add they keys after the fact. I thought that it would put my AWS key in there but apparently not. Tried putting in pub keys and assigning the EXO_PRIVATE_KEY with my private key too. Just repeatedly fails the login. Any suggestions would be appreciated. I'll be out for a few hours.

> Next, you can add any additional authorized_keys you want to use for Exoframe authentication:

$ vim /home/ubuntu/.ssh/authorized_keys
# add any keys you want to use to login into exoframe

**Comment by yamalight** [comment]
Hi @RegEM 
1. `-e EXO_PRIVATE_KEY=your_private_key` is required - it's used as a private key for JWT generation during auth
2. I have not tried running exoframe on windows, but in theory it should work. How exactly does it gets stuck? never executes? have you pointed exoframe to your new server using `exoframe endpoint`?

**Comment by yamalight** [comment]
private key in EXO_PRIVATE_KEY is just the key that's used to encrypt JWT, it's not related to anything else. You can set it to whatever you want, it is just a string. For security purposes I'd recommend to set it to a long random string of characters (e.g. something generated with password generator)

`~/.ssh/authorized_keys` public keys and your personal private key are what's used to login - the same way ssh login works.

**Comment by RegEM** [comment]
Thanks. I figured that, but was confused. 

If it is security issue, maybe the documentation should have it as a <user input variable> instead of as the 'your_private_key' string? 

Because of the security issues (not that I understand them very well), I redid it all, and created new keys for Ec2. 

And now it works fine. 

Cheers, Richard

**Comment by yamalight** [comment]
Cool, glad you figured it out :)
