### ISSUE TITLE
exoframe -u crashes server

### ISSUE THREAD

**Issue by Harjot1Singh** [exoframejs/exoframe#142]
I'm running Ubuntu 18.04 with Docker 18.05.0-ce, build f150324 (edge).

When I do an `exoframe deploy -u` on docker-compose projects, sometimes they fail and commands such as `exoframe ls` stop working, responding with `Error while getting list: HTTPError: Response code 404 (Not Found)`.

The logs show the following:
```
2018-05-25T16:25:41.714Z - info: [exoframe-server] Initializing docker services...
2018-05-25T16:25:41.762Z - info: [exoframe-server] Traefik managment disabled, skipping init..
2018-05-25T16:25:41.772Z - info: [exoframe-server] Server running at: 8080
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'Id' of undefined
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any ideas where this could be coming from?

The only way I've found I'm able to recover is by restarting the Exoframe container.

**Comment by yamalight** [comment]
Hi @Harjot1Singh! Could you please provide a simple test case for that?

**Comment by Harjot1Singh** [comment]
It wouldn't work even if I removed the container, the data and any images - I reinstalled the VPS and the issues seem to be resolved now.

**Comment by yamalight** [comment]
That's really weird. But glad you've resolved it!
Feel free to open more tickets if you have any other issues :)
