### ISSUE TITLE
static deploy error - 'Bad Gateway'

### ISSUE THREAD

**Issue by RegEM** [exoframejs/exoframe#144]
Can I deploy a single jpeg into my swarm on EC2? 

I get this error;

```  name: 'HTTPError',
  host: 'ec2-....compute-1.amazonaws.com',
  hostname: 'ec2-....compute-1.amazonaws.com',
  method: 'POST',
  path: '/deploy',
  protocol: 'http:',
  url: 'http://ec2-....compute-1.amazonaws.com/deploy',
  statusCode: 502,
  statusMessage: 'Bad Gateway',
  headers:
   { 'content-type': 'text/plain; charset=utf-8',
     vary: 'Accept-Encoding',
     date: 'Fri, 25 May 2018 22:16:20 GMT',
     'content-length': '11',
     connection: 'close' } }
Original response: undefined```

I have been struggling to get response from more complicated deploys, so am just trying to make sure I get the simplest deploys working.

**Comment by RegEM** [comment]
Same issue with a single index.html file. 

Whereas I can deploy a Dockerfile. Though not exposing ports properly. Will try verbose on that.

**Comment by RegEM** [comment]
...same error in exoframe-server service logs.
```exoframe-server.1.41jdodc2kc9r@exo-master    | 2018-05-25T18:49:26.080Z - info: [exoframe-server] Server running at: 8080
exoframe-server.1.41jdodc2kc9r@exo-master    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'executeTemplate' of undefined
exoframe-server.1.41jdodc2kc9r@exo-master    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
exoframe-server.1.41jdodc2kc9r@exo-master    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'executeTemplate' of undefined```

**Comment by RegEM** [comment]
I think I've made some progress with the dockerfile deploy. I removed the 'domain; ec2...' from my exoframe.json, and now get the following traefik lines generated. Seems correct to me, but when I open it up in the browser, I get a 404, on a custom page.


```"traefik.backend": "exo-user-ngrok-afda0390",
"traefik.frontend.rule": "Host:ec2-54-227-206-203.compute-1.amazonaws.com;Path:/api", ```

**Comment by RegEM** [comment]
Deploying the html-project test fixture. Deploys..

If I deploy with 'exoframe -vvv' command, I get the url defined in exoframe.json label. 

If I just deploy with 'exoframe', I get a domain I defined somewhere along the way. Might have been in server.config.yml, but the domainbase is false. Running 'docker-machine restart exo-master'.  Seems to be stick for a while, till I deploy something different.

But still a 404.

Doesn't seem to be creating containers when deploying. hmmm...

**Comment by RegEM** [comment]
I can see they are getting rejected via running 'docker service ps'. 

I would think this error state should be shown in 'exoframe list' too, but it's not.

**Comment by yamalight** [comment]
@RegEM could you please describe your exoframe setup and provide a simple test case?

Few notes: 
1. `.jpg` won't deploy automatically as exoframe doesn't have a fitting template for it, so your best option is to provide custom Dockerfile
2. Looks like you are running on AWS, have you made sure you have the required security group permissions assigned? From my experience that is what usually causes problems with deployments
3. `-vvv` just enables verbose logging, just running `exoframe` without it executes exactly same deployment so that shouldn't affect anything but the stuff you see on the screen

**Comment by RegEM** [comment]
Sure. Bear with me, as not much experience as a contributor.

Yes on AWS. Checked Network ACL, VPC routing, and security groups om imstances. Noted if I try to run Docker command when connected b docker-machine ssh to master, that need to run as sudo.

In general followed directions from your tutorial. Had to modify aws-cli commands to  use ```--group-id``` for all lines after the, '# Permit Docker API ports'.

Using powershell, but running the node create gives a nice hint for the follow up env command. They look like this:
```& "C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe" env exo-master | Invoke-Expression```

My service create is like this:
```docker service create `
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock `
  --mount type=bind,source=/home/ubuntu/.exoframe,target=/root/.exoframe `
  --mount type=bind,source=/home/ubuntu/.ssh/authorized_keys,target=/root/.ssh/authorized_keys,readonly `
  -e EXO_PRIVATE_KEY=some string`
  --label traefik.backend=exoframe-server `
  --label traefik.frontend.rule=Host:ec2-54-227-206-203.compute-1.amazonaws.com `
  --label traefik.port=8080 `
  --constraint=node.role==manager `
  --name exoframe-server `
  exoframe/server:develop```

Endpoint: ```exoframe endpoint http://ec2-54-227-206-203.compute-1.amazonaws.com```

Can docker-machine ssh to all three nodes. Swarm seems to be built.
```docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
kpsafdzzvtwg91qc00jjiestt *   exo-master          Ready               Active              Leader
ysvd8ssqevm2bgmxr71efnzau     exo-node1           Ready               Active
uhzlyekwrcl9wluq625lmqfm7     exo-node2           Ready               Active```

Trying various deployments. Latest is from your text fixture with label added as shown.
exoframe.json:
```{
  "name": "test-html-deploy",
  "domain": false,
  "project": "simple-html",
  "restart": "no",
  "labels": {
    "traefik.frontend.rule": "Host:ec2-54-227-206-203.compute-1.amazonaws.com;Path:/html"
  }
}```
index.htm:
```<html lang="en">
<head>
    <title>hello world.</title>
</head>
<body>
    <h1>This is hello world</h1>
    <p>Test test test.</p>
</body>
</html>```

Can't show deployment as buffer too short. Will need to startup worker nodes and redo.

Yes looks like workers can't talk to master.

**Comment by RegEM** [comment]
I'll be away for an hour or two.

**Comment by RegEM** [comment]
Re: Item 3 
> -vvv just enables verbose logging, just running exoframe without it executes exactly same deployment so that shouldn't affect anything but the stuff you see on the screen

I believe the domain was set in a different deployment, in the exsonframe.json. Not sure if I can duplicate the case again, and may very well be I was just mistaken

Restarted my workers, 
```
docker-machine start exo-node1
docker-machine start exo-node2
docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
kpsafdzzvtwg91qc00jjiestt *   exo-master          Ready               Active              Leader
ysvd8ssqevm2bgmxr71efnzau     exo-node1           Ready               Active
uhzlyekwrcl9wluq625lmqfm7     exo-node2           Ready               Active
```
then removed all my deployments.

then deployed the simple-html
```
exoframe -vvv

Deploying current project to endpoint: http://ec2-54-227-206-203.compute-1.amazonaws.com

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying Static HTML project..
[verbose] Building image with tag: exo-gord-test-html-deploy:latest
[verbose] Step 1/3 : FROM nginx:latest
[verbose]

[verbose] {"status":"Pulling from library/nginx","id":"latest"}
[verbose] {"status":"Digest: sha256:0fb320e2a1b1620b4905facb3447e3d84ad36da0b2c8aa8fe3a5a81d1187b884"}
[verbose] {"status":"Status: Image is up to date for nginx:latest"}
[verbose]  ---> ae513a47849c

[verbose] Step 2/3 : COPY . /usr/share/nginx/html
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> ce2c1358901f

[verbose] Step 3/3 : RUN chmod -R 755 /usr/share/nginx/html
[verbose]

[verbose]  ---> Using cache

[verbose]  ---> f291330a9cde

[verbose] {"aux":{"ID":"sha256:f291330a9cde26ba2a4db947b5c35089b32ffb54510ea8a0437634ec4c09cd1a"}}
[verbose] Successfully built f291330a9cde

[verbose] Successfully tagged exo-gord-test-html-deploy:latest

[verbose] Starting serivce with following config:
[verbose] Service successfully started!
[info] Deployment success!
Server response: {
  "message": "Deployment success!",
  "deployments": [
    {
      "ID": "kdlmop8montf8olkfqfrunjkh",
      "Version": {
        "Index": 1327
      },
      "CreatedAt": "2018-05-26T16:54:00.41466205Z",
      "UpdatedAt": "2018-05-26T16:54:00.41466205Z",
      "Spec": {
        "Name": "exo-gord-test-html-deploy-635621c0",
        "Labels": {
          "exoframe.deployment": "exo-gord-test-html-deploy-635621c0",
          "exoframe.project": "simple-html",
          "exoframe.user": "gord",
          "traefik.backend": "exo-gord-test-html-deploy-635621c0",
          "traefik.frontend.rule": "Host:ec2-54-227-206-203.compute-1.amazonaws.com;Path:/html",
          "traefik.port": "80"
        },
        "TaskTemplate": {
          "ContainerSpec": {
            "Image": "exo-gord-test-html-deploy:latest",
            "Isolation": "default"
          },
          "Resources": {
            "Limits": {},
            "Reservations": {}
          },
          "RestartPolicy": {
            "Condition": "none",
            "MaxAttempts": 1
          },
          "Placement": {},
          "ForceUpdate": 0,
          "Runtime": "container"
        },
        "Mode": {
          "Replicated": {
            "Replicas": 1
          }
        },
        "UpdateConfig": {
          "Parallelism": 2,
          "Delay": 10000000000,
          "FailureAction": "pause",
          "MaxFailureRatio": 0,
          "Order": "start-first"
        },
        "Networks": [
          {
            "Target": "jc8ttym1e6tri9u87m0l897ni"
          }
        ]
      },
      "Endpoint": {
        "Spec": {}
      }
    }
  ],
  "level": "info"
}

Your project is now deployed as:

   ID                                       URL                                                         Hostname
   exo-gord-test-html-deploy-635621c0       ec2-54-227-206-203.compute-1.amazonaws.com;Path:/html       Not set
```
```
docker service ps --no-trunc kdlmop8montf
ID                          NAME                                   IMAGE                              NODE                DESIRED STATE       CURRENT STATE            ERROR                                               PORTS
wecji97e7t9efgtne5taqvbw8   exo-gord-test-html-deploy-635621c0.1   exo-gord-test-html-deploy:latest   exo-node2           Shutdown            Rejected 2 minutes ago   "No such image: exo-gord-test-html-deploy:latest"
```

**Comment by RegEM** [comment]
I had to
```
docker-machine regenerate-certs exo-node1
```
after restarting, so I could ssh into them. Will retry the deploy and will comment again if any change.

**Comment by yamalight** [comment]
Added a ticket for it here: https://github.com/exoframejs/exoframe/issues/145

**Comment by RegEM** [comment]
Ok. If I can try anything for you, let me know.
I was trying to sort through the swarm networking, but it's greek to me at this juncture. Couldn't get it to pull from the master, etc.. Some attempts:
```
ubuntu@exo-node2:~$ sudo docker pull 10.0.0.38:2377/exo-gord-test-html-deploy
Using default tag: latest
Error response from daemon: Get https://10.0.0.38:2377/v2/: x509: cannot validate certificate for 10.0.0.38 because it doesn't contain any IP SANs
ubuntu@exo-node2:~$ sudo docker pull ec2-54-227-206-203.compute-1.amazonaws.com:2377/exo-gord-test-html-deploy
Using default tag: latest
Error response from daemon: Get https://ec2-54-227-206-203.compute-1.amazonaws.com:2377/v2/: x509: certificate is valid for swarm-manager, kpsafdzzvtwg91qc00jjiestt, swarm-ca, not ec2-54-227-206-203.compute-1.amazonaws.com
ubuntu@exo-node2:~$ sudo docker pull kpsafdzzvtwg91qc00jjiestt:2377/exo-gord-test-html-deploy
Using default tag: latest
Error response from daemon: Get https://kpsafdzzvtwg91qc00jjiestt:2377/v2/: dial tcp: lookup kpsafdzzvtwg91qc00jjiestt on 10.0.0.2:53: no such host
ubuntu@exo-node2:~$ sudo docker pull 54.227.206.203:2377/exo-gord-test-html-deploy
Using default tag: latest
Error response from daemon: Get https://54.227.206.203:2377/v2/: x509: cannot validate certificate for 54.227.206.203 because it doesn't contain any IP SANs
```
Originally I was trying to start with the AWS template, but happened to see your tutorial. As the template creates the vpc, permissions and logging I thought it would be a good way to start. https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl

Ran into an issue with that though (I forget what it was), so your tutorial seemed to be a better way to go.

**Comment by yamalight** [comment]
@RegEM you won't be able to "pull" image from master, what you can do is use [save](https://docs.docker.com/engine/reference/commandline/save/) on master and [load](https://docs.docker.com/engine/reference/commandline/load/) on workers to fix the problem (that was my initial though for very basic fix implementation). But that's not very nice. Your suggestion with private registry sounds way better IMO

**Comment by RegEM** [comment]
Sure. I believe the pulling is just a means to test that the registry works. 

The manager should control what the workers do. Global mode each one gets a copy, Replicated, I suppose the copies get distributed as per some algorithm, and determined load level seen from the workers. 

Not sure what the usefulness would be without having the private registry. I'm easily confused though.

I see in the replicated mode, I can run 10 copies at a time all on my master, etc... I imagine the exoframe service can be replicated too, though don't know if that would make sense.

**Comment by RegEM** [comment]
I'll close this Tim. And comment further on the new thread. Although I think I have another issue, it's not really descibed here.

**Comment by yamalight** [comment]
@RegEM ok, cool. feel free to open more issues on other stuff :)
