### ISSUE TITLE
Sync images across all nodes when running in swarm mode

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#145]
When running in swarm mode and building local images - Exoframe needs to sync built image to all nodes to make execution reliable. See #144 for more info.

**Comment by yamalight** [comment]
Possible way to sync: https://stacktoheap.com/blog/2015/11/22/sharing-docker-images-without-registry/

**Comment by RegEM** [comment]
I had though much of this was automatically done as part of the swarm. And if one manager dies, the workers would need to pull images from another manager. But I really don't know how you have exoframe built.
I went back to the reference, https://docs.docker.com/engine/swarm/services/#create-a-service-using-an-image-on-a-private-registry which I thought was close to what exoframe would be doing, but maybe it isn't.

**Comment by RegEM** [comment]
I don't know if this is the way, but a local registry can be setup. 

Looking at the images on the master, it looks like the tagging just gives a way to have an unauthenticated way to pull images. I suggest if the registry has the proper config, the tagging and pushing might not be necessary. Just a guess...

Again. I dunno why this isn't automatic in the swarm. Maybe it is if the registry is properly configured..

I can pull now as shown, but I don't know whether the swarm is actually any closer to being correct. Still getting 404. Maybe if this is done before 'start' of the container.
```
docker service create --name registry --publish published=5000,target=5000 registry:2

exoframe
- giving image id of f291330a9cde 

docker-machine ssh exo-master sudo docker tag f291330a9cde localhost:5000/exo-gord-test-html-deploy
docker-machine ssh exo-master sudo docker push localhost:5000/exo-gord-test-html-deploy

docker-machine ssh exo-master sudo docker pull localhost:5000/exo-gord-test-html-deploy
docker-machine ssh exo-node1 sudo docker pull localhost:5000/exo-gord-test-html-deploy
docker-machine ssh exo-node2 sudo docker pull localhost:5000/exo-gord-test-html-deploy
```
https://docs.docker.com/docker-for-aws/deploy/#images-in-private-repos
https://docs.docker.com/registry/configuration/

**Comment by RegEM** [comment]
Something along these lines?
https://medium.com/@zh3w4ng/docker-swarm-with-private-registry-for-micro-services-behind-corporate-proxy-bafb349d0b9c

**Comment by yamalight** [comment]
@RegEM Exoframe doesn't use any registries yet - the images are just built on master node. 
Using a registry would actually be a better approach. Would require a bit more time to build, but would definitely be more efficient 🤔

**Comment by RegEM** [comment]
#144 Left a comment re: modes, and closed that issue.

**Comment by yamalight** [comment]
Moved to swarm plugin repo.
