### ISSUE TITLE
fork - questions

### ISSUE THREAD

**Issue by RegEM** [exoframejs/exoframe#149]
Hi Tim. I am forking your project. Pretty much the first time I am going through this process.

I see when I run 'npm link', as directed in your contributor guidlines, that the package-lock.json gets significantly modified.

Should I leave it in it's new form? Or return it to the copy in your repository? 

I ran thru the forking process one time, setting up yarn & travis. It built semi successfully a couple of times, but then crapped out after I was trying to modify the api_key info in travis.yml. So I am starting over. Any direction on that would be appreciated re: this key use, if you have a moment. Or please direct me to any videos you have created that illustrate your build environment.

Thanks, Richard

**Comment by yamalight** [comment]
Hey @RegEM,

As you might've noticed - Exoframe primarily uses yarn (and `yarn.lock`), so if you are using npm - I'd just leave the `package-lock.json` out of git for now 🤔 
If you are speaking about `yarn.lock` - feel free to modify it as needed, don't see any harm in updating it with newer versions (as long as the tests pass) 😄

**Comment by RegEM** [comment]
Ok. I'll try that. 

I think I had probably ran npm update too, on my first forking try. The yarn command I ran, seemed to be 100% ok.

Being on windows, I run into lots of building errors. Part of the reason I am looking at tools like exoframe/docker deployments. Tried now as well, but like to use my own servers.

**Comment by yamalight** [comment]
Feel free to ping me if you need anything - will be happy to help!
I typically use Win10 + WSL with locally installed Docker - that combo seems to be working just as good as MacOS + Docker for me 🤔

**Comment by RegEM** [comment]
WSL. I forgot all about that. I see it's enabled.

Which linux distribution do use in WSL?

**Comment by yamalight** [comment]
I believe it's Ubuntu-based. MS now has [pretty extensive docs](https://docs.microsoft.com/en-us/windows/wsl/about) on it too

**Comment by RegEM** [comment]
Thanks Tim. Much appreciated. 
I'll close this.
