### ISSUE TITLE
traefik.docker.network is missing

### ISSUE THREAD

**Issue by JoyceBabu** [exoframejs/exoframe#151]
I am trying to run exoframe-server with an existing traefik installation. But the deployed container does not have either `traefik.enable` or `traefik.docker.network` labels. I am using latest exoframe-server image released 2 weeks ago.

```
            "Labels": {
                "exoframe.deployment": "exo-joyce-test-93ed4a10",
                "exoframe.project": "exo-joyce-test",
                "exoframe.user": "joyce",
                "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
                "traefik.backend": "<my-host>",
                "traefik.frontend.rule": "Host:<my-host>"
            },
```

**Comment by yamalight** [comment]
Yes, currently Exoframe doesn't add those labels - but probably should 🤔
I'll try to add it for the next release - and PRs welcome as always 😄

**Comment by JoyceBabu** [comment]
Are you sure, because I am seeing this in docker/start.js

https://github.com/exoframejs/exoframe-server/blob/150e9a772c77403e1059ea7c6a9e8114c8a69caa/src/docker/start.js#L66

**Comment by yamalight** [comment]
@JoyceBabu this is a method exposed for setup recipes. the one that's used during deployments is `start` below this one. which actually means I need to refactor the code to use it too for the sake of consistency 🤔
