### ISSUE TITLE
don`t run letsencrypt

### ISSUE THREAD

**Issue by kimorkim** [exoframejs/exoframe#156]
I want to apply TLS.

#server.config.yml
![image](https://user-images.githubusercontent.com/5179851/42491744-0ec3f5aa-8451-11e8-9f4a-cd60a7557c30.png)

but, page is not connected.
![image](https://user-images.githubusercontent.com/5179851/42491805-533907ca-8451-11e8-8280-9a00f53f0e68.png)
![image](https://user-images.githubusercontent.com/5179851/42491826-646e97a8-8451-11e8-830d-1e656799da8f.png)
only repeat redirect page.

What am I supposed to do?

**Comment by yamalight** [comment]
Hi,

1. Make sure you have `letsencrypt: true` in the config - right now I see `false`
2. After changing the config you need to manually stop and remove traefik container. After that - restart exoframe-server container to allow it re-initilize traefik with new config (that's also mentioned in the docs)

Then it should work.
Additional things to check if it still doesn't:
- Make sure your port 443 is not taken by anything 
- Check traefik logs after it has been created to see if there are any abnormalities

Let me know if that helps

**Comment by kimorkim** [comment]
@yamalight 
Sorry. I took the wrong screen shot.
Let's take a traefik log first.
Then I'll let you know what's going on.

**Comment by kimorkim** [comment]
First, I floated the exoframe as follows.
```
docker service create \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/home/tooniz/exoframe-folder,target=/root/.exoframe \
  --mount type=bind,source=/home/tooniz/.ssh/authorized_keys,target=/root/.ssh/authorized_keys,readonly \
  -e EXO_PRIVATE_KEY=tooniznext \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:tooniz.usbsync.net \
  --label traefik.port=8080 \
  --constraint=node.role==manager \
  --name exoframe-server \
  exoframe/server
```
#### server.config.yml
```
debug: false
letsencrypt: true
letsencryptEmail: kimorkim@gmail.com
compress: true
baseDomain: false
cors: false
updateChannel: stable
traefikImage: 'traefik:latest'
traefikName: exoframe-traefik
traefikArgs: []
exoframeNetwork: exoframe
exoframeNetworkSwarm: exoframe-swarm
swarm: true
publicKeysPath: /root/.ssh
```

#### docker service
![image](https://user-images.githubusercontent.com/5179851/42501126-fa1d6cf4-846d-11e8-8e4f-320138758abe.png)

#### docker process
![image](https://user-images.githubusercontent.com/5179851/42501162-12458b2c-846e-11e8-8c8a-500e05d067de.png)

#### traefik log
```
time="2018-07-10T09:16:54Z" level=error msg="Failed to read new account, ACME data conversion is not available : open /var/acme/acme.json: no such file or directory"
time="2018-07-10T09:17:19Z" level=error msg="Unable to obtain ACME certificate for domains \"tooniz.usbsync.net\" detected thanks to rule \"Host:tooniz.usbsync.net\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[tooniz.usbsync.net] acme: Error 429 - urn:ietf:params:acme:error:rateLimited - Error finalizing order :: too many certificates already issued for exact set of domains: tooniz.usbsync.net: see https://letsencrypt.org/docs/rate-limits/\n"
```

Do you happen to know the problem?

**Comment by yamalight** [comment]
From the traefik error message it seems like you are just getting rate-limited by letsencrypt.
See their page for more info: https://letsencrypt.org/docs/rate-limits/
So, you just need to wait before rate-limit it refreshed and it should start working.

**Comment by kimorkim** [comment]
Hmm.
I didn't do anything special, only used exoframe.
I don't know why the limit was imposed.
I've got it. Thanks for your help. I'll close the issue.

**Comment by yamalight** [comment]
@kimorkim they have pretty strict limits. 
same had that happen to me when I forgot to change DNS entries for domain before starting traefik.
just wait a bit and try again - if the limits error goes away, but it still doesn't work - feel free to re-open the issue, I'll gladly help to figure out what's wrong 😃
