### ISSUE TITLE
404 in swarm mode

### ISSUE THREAD

**Issue by smirnp** [exoframejs/exoframe#161]
Hi!

I'm trying the following config:
`docker service create --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock --mount type=bind,source=/opt/exoframe,target=/root/.exoframe --mount type=bind,source=/home/-------/.ssh/authorized_keys,target=/root/.ssh/authorized_keys,readonly -e EXO_PRIVATE_KEY=key1 --label traefik.backend=exoframe-server --label traefik.frontend.rule=Host:exoframe.local --label traefik.port=8080 --constraint=node.role==manager --name exoframe-server exoframe/server -v`

The service is converged, two containers are started, but accessing http://exoframe.local gives the "404 service not found" message. Login is not working due to the endpoint not found message

Running fully the same in non swarm mode gives the "Powered by exoframe" image. And login works.

**Comment by yamalight** [comment]
What is that `-v` at the very end? 🤔

**Comment by smirnp** [comment]
Sorry, this is my attempts to verbose output of docker, but it returns nothing. As well as 404 without it. 
During running: it outlputs something like "detecting failed state....waiting until contaiters will become stable ... 1..2...3.. etc, service converged"

**Comment by yamalight** [comment]
The stuff you pass after image name goes as args to command execute _within_ the container.
If removing it doesn't help - please share the logs from exoframe server and traefik here.

**Comment by smirnp** [comment]
Where these logs are written? I have debug: true in /opt/exoframe/server.config.yml, but the only thing I see in console is:
```
yqohgyv1oquuf6hvk1c1ijlod
overall progress: 0 out of 1 tasks 
1/1: ready     [======================================>            ] 
verify: Detected task failure 

overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Waiting 1 seconds to verify that tasks are stable... 

verify: Service converged 


```

**Comment by yamalight** [comment]
You can get the logs from services using standard [docker logs](https://docs.docker.com/engine/reference/commandline/logs/) command

**Comment by smirnp** [comment]
Everything started perfect after reboot.
