### ISSUE TITLE
Unable to connect (certainly config issues)

### ISSUE THREAD

**Issue by derek-adair** [exoframejs/exoframe#162]
Excuse the novice sys admin question but I cant figure out how to get my client logged into the server.  I have two ec2 instances, one for development and one for production.  

**Clues**

1. I am able to ssh just fine w/ my .pem
2. I've opened all outbound ports on my client machine
3. 443/22 are open to my dev box.  8080/80 are open to the world

**Error**
```
Logging in to: [redacted ip]                                                                                                           
 ? Username: user
? Private key: REDACTED.pem
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error getting login request phrase. Make sure your endpoint is correct! RequestError: connect ECONNREFUSED [redacted ip]:443
```
Clearly something wrong w/ the config but i am just... not getting it.  I'm not sure if i have the traefik host improperly configured, the endpoint misconffigured or both.

~/.exoframe/cli.config.yml: 
```
endpoint: '{MY_PRDUCTION_IP}'
```

**Docker run command:**
```
➜  ~ docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \                                                                                            
  -v  /home/{my_user}/exoframe:/root/.exoframe \
  -v /home/{my_user}/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \                                                                     
  -e EXO_PRIVATE_KEY=/home/{my_user}/redacted.pem \
  --label traefik.backend=exoframe-server \                                                                                                
  --label traefik.frontend.rule=Host:exoframe.{my_ip} \
  --restart always \                                                                                                                       -
  --name exoframe-server \
  exoframe/server
```

**Comment by derek-adair** [comment]
Is EXO_PRIVATE_KEY supposed to be my ssh private key? am i suppose to generate one? does exoframe generate this?

**Comment by yamalight** [comment]
I see that you are trying to working with your IP address - Exoframe and Traefik expect domains and I'm not sure whether they'll work with just IPs as I've never tested it. 🤔 
You could use either the default one provided by AWS or just alias you IP to some domain in /etc/hosts - then it should work.

EXO_PRIVATE_KEY is a private key used for session encryption - it can be any random string. Maybe I should rename it to evade confusion 🤔

**Comment by htkoca** [comment]
I would love some documentation regarding `EXO_PRIVATE_KEY`. I scoured the internet to figure out what it is lol

**Comment by yamalight** [comment]
@htkoca it's just a string that's used to encrypt JWT session (so, private key). can be anything, better if it's long and unique.

**Comment by derek-adair** [comment]
maybe call it EXO_HASH? i dunno i definitely assumed EXO_PRIVATE_KEY was a pem i would supply.  Private key is probably not the best name.

**Comment by yamalight** [comment]
@derek-adair it's not the hash itself though, it's a private key used to encrypt the session 🤔

**Comment by derek-adair** [comment]
oh so it IS actually a .pem, thats a fine name in that  ase xD

**Comment by yamalight** [comment]
it is not the PEM, it's just a string. you can use your PEM string there if you want to. 
but it is just a private key that's used for JWT (session) encryption.
