### ISSUE TITLE
Add frontend auth support

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#168]
Traefik 1.7 introduced auth support for front-ends.
It can be achieved by using the following label:
```
# Sets basic authentication for that frontend in CSV format: User:Hash,User:Hash [2]
traefik.frontend.auth.basic=EXPR

[2] traefik.frontend.auth.basic=EXPR: To create user:password pair, it's possible to use this command echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g. The result will be user:$$apr1$$9Cv/OMGj$$ZomWQzuQbL.3TRCS81A1g/, note additional symbol $ makes escaping.
```
We should add support for this in config file.

**Comment by uLan08** [comment]
Hi, I would like to take this on!

**Comment by uLan08** [comment]
Hey @yamalight , Do I need to update code in the server repo?

**Comment by yamalight** [comment]
@uLan08 you'd actually need to work a bit with both.
here's the outline of what needs to be done:
1. Add auth field support to [`exoframe config` method](https://github.com/exoframejs/exoframe/blob/master/src/commands/config.js) in cli
2. Read auth field from config on server and when needed add corresponding labels during deployment ([here](https://github.com/exoframejs/exoframe-server/blob/master/src/docker/start.js#L61) and [here](https://github.com/exoframejs/exoframe-server/blob/master/src/docker/start.js#L229)) in server
3. Document that in [config docs](https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#project-config-file)

**Comment by uLan08** [comment]
I see... So it should be a new field and should not be under labels right?

**Comment by uLan08** [comment]
Btw, I just saw that it's under a new format.

```
traefik.frontend.auth.basic.users=EXPR | Sets the basic authentication to this frontend in CSV format: User:Hash,User:Hash [2]
```

https://docs.traefik.io/configuration/backends/docker/#on-containers

**Comment by yamalight** [comment]
@uLan08 yep, the idea is to give exoframe users a very simple way of doing it.
Nice catch on the format change! 👍

**Comment by yamalight** [comment]
@uLan08 thanks for great contributions!

I'd want one more (bonus) thing if you're up for it (if not - no worries, I can add that later myself) - `exoframe config` should ask user for username and password (instead of simple `user:hash` string) and auto-encrypt that password 🤔

**Comment by uLan08** [comment]
@yamalight Alright, sounds interesting. I'll try and have a go at it.

**Comment by yamalight** [comment]
@uLan08 oh, crap. I'm sorry, I thought I'd definitely answered you 😮
yes, the idea is to allow entering multiple user:pass pairs and basically ask after each one - `add more?`

**Comment by yamalight** [comment]
There seems to be an inquirer plugin for this 🤔 
https://github.com/nathanloisel/inquirer-recursive

**Comment by uLan08** [comment]
That's alright. I played around with this a bit last time but I ran into some issue and I wasn't able to finish it. I'll look at it again and try implementing multiple user:pass pairs.

**Comment by yamalight** [comment]
Feel free to ask here if you need help with that - I'll be more than happy to assist.
And once again - thanks for your contributions 😃

**Comment by uLan08** [comment]
@yamalight What is the credentials to login into the exoframe server?

**Comment by yamalight** [comment]
@uLan08 you mean login with `exoframe login`? that uses your private key. if you are not talking about this login - please elaborate a bit.

I think this one was generated with yarn 1.8, but not 100% sure. feel free to update it with new version 👍

**Comment by yamalight** [comment]
@uLan08 405 means exoframe server cannot read your public keys file. 
how did you start you server? using docker or locally?
if using docker - have you linked your `authorized_keys` to it?
if locally - do you have `~/.ssh/authorized_keys` in your home folder?

**Comment by uLan08** [comment]
@yamalight Ah! I am running it locally, adding an `authorized_keys` file did the trick. Is this in the documentation somewhere? I guess I missed it.

**Comment by yamalight** [comment]
@uLan08 there is mention of this in server config docs, but now that I'm thinking about it - there's no "how to setup server for dev" docs. probably should add this 🤔

**Comment by yamalight** [comment]
This is now ready to ship. Thanks to the @uLan08 
Closing the issue.
