### ISSUE TITLE
Modern docker-compose deployments are overwriting each other

### ISSUE THREAD

**Issue by niieani** [exoframejs/exoframe#175]
`exoframe-server` uses a constant as the project name for *ALL* docker-compose-based deployments. This causes any >=`v3.6` deployment to automatically remove any previous ones, which means you can have a maximum one docker-compose deployment if you use a modern version.

I've created a fix https://github.com/exoframejs/exoframe-server/pull/16, but it needs tests. I don't have the time to work on it at this moment, so if anybody else stumbles upon this, feel free to start off your work there.

An additional issue with this is that in order to migrate pre-existing deployments using docker-compose you need to manually change the `com.docker.compose.project` label of every container, or re-create the deployments after manually removing each container.

**Comment by yamalight** [comment]
Thanks for opening this!

Old PR for the reference: https://github.com/exoframejs/exoframe-server/pull/16

**Comment by yamalight** [comment]
Ready to ship.
