### ISSUE TITLE
Move the server documentation to the main repo

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#177]
We currently have a small slice of Exoframe docs related to server located in [server repo](https://github.com/exoframejs/exoframe-server). 
This is proving to be pretty inconvenient. We need to move the important bits from that readme into this repo's [docs folder](https://github.com/exoframejs/exoframe/tree/master/docs) and replace the readme stuff with link to new file.

**Comment by Jose-27** [comment]
I can take a look at it

**Comment by yamalight** [comment]
@andrasbacsai I've left a few requests for changes there, but looks good, thank you! 👍 

@Jose-27 you still have a chance to send a PR to server repo to clean up the docs there 😉

**Comment by Jose-27** [comment]
pull request created!

**Comment by yamalight** [comment]
@Jose-27 thanks! requested a few minor changes to it

**Comment by yamalight** [comment]
This is now done 🤔
