### ISSUE TITLE
Exoframe is not pulling needed images when using recipe

### ISSUE THREAD

**Issue by henrikcoll** [exoframejs/exoframe#183]
using: `exoframe setup exoframe-recipe-wordpress`

outputs:
```
Executing recipe with user configuration...
Log:
Error: (HTTP code 404) no such container - No such image: mariadb:latest

Error executing recipe!
```

its fixed by logging in to the server with ssh and running `docker pull mariadb:latest`

**Comment by yamalight** [comment]
@henrikcoll thanks for reporting! I think it should be relatively easy to fix by pre-pulling image in recipes (when running not in swarm mode) 🤔

**Comment by yamalight** [comment]
@henrikcoll thanks for your help!
fixed version should now be on npm.
