### ISSUE TITLE
Bad Gateway problems

### ISSUE THREAD

**Issue by JoeLanglois** [exoframejs/exoframe#186]
Hey there, I have been loving Exoframe so far but having some problems with my latest node app.

The problem is once deployed (with success), when trying to access the URL, it always returns `Bad Gateway` with status 502.

I can `docker exec CONTAINER wget localhost/login` and I get my login page like expected, but not from an external place.

Any idea how I can debug that?

Thanks!

**Comment by JoeLanglois** [comment]
When checking docker logs, it says the app is listening on `127.0.0.1:80` so ports are correctly configured.

**Comment by yamalight** [comment]
@JoeLanglois can you please try binding it to `0.0.0.0:80` instead of `127.0.0.1`?

**Comment by JoeLanglois** [comment]
It works! Thanks, didn't know it made a difference!

**Comment by yamalight** [comment]
Cool, glad it was that easy :)
