### ISSUE TITLE
exoframe login No private key to select

### ISSUE THREAD

**Issue by zandoan** [exoframejs/exoframe#187]
I logged in to AWS EC2 instance and configured the server

<img width="1004" alt="screen shot 2018-12-14 at 2 08 13 am" src="https://user-images.githubusercontent.com/45378229/49997190-bcca4900-ff45-11e8-9198-1829fe063ef3.png">

I checked authorized_keys has data
<img width="880" alt="screen shot 2018-12-14 at 2 09 46 am" src="https://user-images.githubusercontent.com/45378229/49997249-eb482400-ff45-11e8-98b8-6c94a8cb4260.png">

When I used "exoframe login" to login to the server and entered the user, then there was no private key for me to select:
<img width="849" alt="screen shot 2018-12-14 at 2 07 50 am" src="https://user-images.githubusercontent.com/45378229/49997335-2185a380-ff46-11e8-8957-8dfd7e5a9b2c.png">
Am I missing any step to see the private key options and login successfully? Thanks.

**Comment by yamalight** [comment]
@zandoan by default exoframe picks up your private keys from `~/.ssh/` folder. Do you have them there? 🤔

**Comment by zandoan** [comment]
It worked @yamalight. Thanks for the clarification 👍

**Comment by yamalight** [comment]
@zandoan cool, glad it was that easy to solve :)
