### ISSUE TITLE
Document private key format requirements

### ISSUE THREAD

**Issue by pojntfx** [exoframejs/exoframe#188]
Hello,

I was just setting up a new Fedora installation, `ssh-copy-id`'s my SSH key to my Exoframe server and tried to log in, but the above error occurs. SSH'ing into the server works just fine.

The exact error message:

```bash
 ~ exoframe login
Logging in to: https://exoframe.services.learn-chinese.tk
? Username: pojntfx
? Private key: id_rsa
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error generating login token! Make sure your private key password is correct Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
```

My system:

```bash
 ~ neofetch 
          /:-------------:\           pojntfx@pojntfx-x230-fedora 
       :-------------------::         --------------------------- 
     :-----------/shhOHbmp---:\       OS: Fedora 29 (Workstation Edition) x86_64 
   /-----------omMMMNNNMMD  ---:      Host: 34382BG ThinkPad X230 Tablet 
  :-----------sMMMMNMNMP.    ---:     Kernel: 4.18.16-300.fc29.x86_64 
 :-----------:MMMdP-------    ---\    Uptime: 1 day, 8 hours, 13 mins 
,------------:MMMd--------    ---:    Packages: 1739 (rpm), 24 (flatpak), 18 (snap) 
:------------:MMMd-------    .---:    Shell: bash 4.4.23 
:----    oNMMMMMMMMMNho     .----:    Resolution: 1366x768 
:--     .+shhhMMMmhhy++   .------/    DE: GNOME 3.30.2 
:-    -------:MMMd--------------:     Theme: Adwaita-dark [GTK2/3] 
:-   --------/MMMd-------------;      Icons: Adwaita [GTK2/3] 
:-    ------/hMMMy------------:       Terminal: gnome-terminal 
:-- :dMNdhhdNMMNo------------;        CPU: Intel i5-3320M (4) @ 3.300GHz 
:---:sdNMMMMNds:------------:         GPU: Intel 3rd Gen Core processor Graphics Controller 
:------:://:-------------::           Memory: 6336MiB / 7793MiB 
:---------------------://

 ~ exoframe --version
3.3.0

 ~ openssl version
OpenSSL 1.1.1 FIPS  11 Sep 2018

 ~ node --version
v11.4.0
```

Would be awesome if someone could help me here!

**Comment by yamalight** [comment]
@pojntfx how have you generated your private key? (i.e. what arguments have you used)

**Comment by pojntfx** [comment]
"The Stock Way", that is:

```bash
 ~ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/pojntfx/.ssh/id_rsa): /home/pojntfx/.ssh/id_rsa_2
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/pojntfx/.ssh/id_rsa_2.
Your public key has been saved in /home/pojntfx/.ssh/id_rsa_2.pub.
The key fingerprint is:
SHA256:XNLMJGBiItN0yARfoLno6olfeBAgUS6BlTLuh4IvL30 pojntfx@pojntfx-x230-fedora
The key's randomart image is:
+---[RSA 2048]----+
|XXB+= o.. .      |
|=X== o   *       |
|=o+     . =      |
|.+ .   . o       |
|= o     S        |
|+o +             |
|.+o o            |
|= +oE            |
|+Bo.             |
+----[SHA256]-----+
```

**Comment by yamalight** [comment]
@dggodfrey ah, that's a good point!
that's true - node-jsonwebtoken currently only support PEM formatted keys.
I should probably document that 🤔

**Comment by yamalight** [comment]
Wait, that's odd. I remember using github's guide to generate test private key. So it's not _just_ PEM 🤔 
OK, I definitely gotta document this 😑

**Comment by yamalight** [comment]
I think it has to be RSA key - that might be the problem here.
Gotta see if there's a way to accept all the keys and auto-detect type 🤔

**Comment by dggodfrey** [comment]
It does have to be an RSA key. Otherwise, node-jsonwebtoken gets cranky. I also had to do the PEM option because `-t rsa` would generate an rsa key, but it was still encrypted as 'RFC4716', which would cause node-jsonwebtoken to not work. It must be an update to OpenSSL. Because I had to do all these different flags on my MBP, but didn't on my old Ubuntu server (which hasn't been updated in years - probably need to do that... 🤔).

Only reason I knew where to look was because I was having a similar problem at work!

Ps. I am happy to submit a PR to update documentation :)

**Comment by yamalight** [comment]
@dggodfrey would highly appreciate the PR!

I think it should be possible to use other types of keys - at least I think node's crypto module does knows how to work with them. Need to dig around a bit 🤔

**Comment by yamalight** [comment]
@pojntfx are you still having the issue? if the stuff above helped resolve it - I'll close the ticket

**Comment by pojntfx** [comment]
@yamalight Yes, it's working, thanks a lot for your help!

Exact steps I took:
```bash
 learn-chinese-platform master ssh-keygen -t rsa -b 4096 -m 'PEM' -f $HOME/.ssh/id_rsa_exoframe
 learn-chinese-platform master ssh-copy-id root@46.101.106.53
 learn-chinese-platform master exoframe login
Logging in to: https://exoframe.services.learn-chinese.tk
? Username: pojntfx
? Private key: id_rsa_exoframe
? Private key passpharse (leave blank if not set): [hidden]
Successfully logged in!
```

**Comment by yamalight** [comment]
@pojntfx great! thanks for sharing this 👍
