### ISSUE TITLE
Deploy -u not updating in swarm mode

### ISSUE THREAD

**Issue by EpicKiwi** [exoframejs/exoframe#197]
First, Thanks to everyone making this project because it's awesome !

I have a single node docker swarm and a traefik service manually installed. Deployment works well but updating not so much...

When I execute `deploy -u` (with and without token) the swarm service is maybe updated but the container aren't restarted, it's still the same container running the outdated code. Updating works only when I change `exoframe.json` or when I add a Dockerfile to switch from NodeJs mode to Dockerfile mode.

Finally, when the update succeed, the CLI take more time than when it's not updating. But the result in the console is always the same (success, showing domain and id).

Maybe I missed something about the updating process, for now I need to remove the last deployment and create another to update my code.

EDIT : It's seems to be a problem with swarm mode. If I scale the deployed service to 0 (no container running at all) and scaling back to 1 the container take the new version.

---

1. Turn docker in swarm mode
2. Create `traefik-net` network
3. Create traefik service (I followed the [traefik doc](https://docs.traefik.io/user-guide/swarm-mode/))
4. Create exoframe-server service
5. Config `swarm: true`, `traefikImage: false`, `exoframeNetwork: traefik-net`
6. Deploy with `exoframe` NodeJs or Dockerfile (works well)
7. Update with `exoframe -u` same directory

**Comment by yamalight** [comment]
@EpicKiwi that definitely sounds like a bug.
could you please create a simple repro case for this so I can test it?

**Comment by EpicKiwi** [comment]
Of course yes, I never done that before. Tell me if you want more details.

---

1. Turn docker in swarm mode
2. Create `traefik-net` network
3. Create traefik service (I followed the [traefik doc](https://docs.traefik.io/user-guide/swarm-mode/))
4. Create exoframe-server service
5. Config `swarm: true`, `traefikImage: false`, `exoframeNetwork: traefik-net`
6. Deploy with `exoframe` NodeJs or Dockerfile (works well)
7. Update with `exoframe -u` same directory

---

For now, I can update by scaling to 0 the deployed service and scaling to 1 after. But it isn't a one command deployment anymore :wink:

**Comment by yamalight** [comment]
@EpicKiwi is project a http server-based node app? or do you have something more complex there? 🤔

**Comment by EpicKiwi** [comment]
It's a dead simple app :

https://github.com/EpicKiwi/epickiwi-web

**Comment by yamalight** [comment]
@EpicKiwi got it! will try to triage this in the next few days 🤔

**Comment by yamalight** [comment]
@EpicKiwi I just tried to reproduce this locally and it seems to work correctly (with [test node project](https://github.com/exoframejs/exoframe-server/tree/master/test/fixtures/node-project)) 🤔 
Have you done any additional changes to the project config maybe?

**Comment by EpicKiwi** [comment]
I known and installed traefik first and, after some research, I found exoframe.
I didn't want to re-install traefik because I'm installing exoframe and tried to deal with my infrastructure.
(I'm an hobbyist experimenting with docker-based infrastructures)

**Comment by EpicKiwi** [comment]
My `exoframe.json`:

```json
{
  "name": "epickiwi-web",
  "restart": "always",
  "domain": "epickiwi.fr"
}
```

And my log (it's big):

```sh-session
$ exoframe -u -vvv
Updating current project to endpoint: http://deployment.epickiwi.fr

No .exoframeignore file found, using default ignores

Ignoring following paths: [ '.git', 'node_modules', '.exoframeignore' ]
[info] Deploying Dockerfile project..
[verbose] Building image with tag: exo-epickiwi-epickiwi-web:latest
[verbose] Step 1/6 : FROM node
[verbose] 

[verbose] {"status":"Pulling from library/node","id":"latest"}
[verbose] {"status":"Digest: sha256:5ea9b2d04e1da959087d93289bdcfa5011c3a173bddf3eaf98553676d28b8f63"}
[verbose] {"status":"Status: Image is up to date for node:latest"}
[verbose]  ---> 72ff1a4450d9

[verbose] Step 2/6 : COPY . /home
[verbose] 

[verbose]  ---> 5e21ca78d50c

[verbose] Step 3/6 : WORKDIR /home
[verbose] 

[verbose]  ---> Running in e63ee368aecf

[verbose] Removing intermediate container e63ee368aecf

[verbose]  ---> b122661b36f7

[verbose] Step 4/6 : RUN cd /home && npm i
[verbose] 

[verbose]  ---> Running in aa711a06d037

[verbose] 
> nodemon@1.18.9 postinstall /home/node_modules/nodemon
> node bin/postinstall || exit 0


[verbose] Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate


[verbose] npm
[verbose]  
[verbose] WARN
[verbose]  
[verbose] optional
[verbose]  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):

[verbose] npm
[verbose]  
[verbose] WARN
[verbose]  
[verbose] notsup
[verbose]  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

[verbose] 

[verbose] added 279 packages from 163 contributors and audited 2376 packages in 9.531s

[verbose] found 0 vulnerabilities


[verbose] Removing intermediate container aa711a06d037

[verbose]  ---> 3d826023d435

[verbose] Step 5/6 : EXPOSE 80
[verbose] 

[verbose]  ---> Running in 4cb9031a1c13

[verbose] Removing intermediate container 4cb9031a1c13

[verbose]  ---> 4ea58244ae13

[verbose] Step 6/6 : CMD npm run start
[verbose] 

[verbose]  ---> Running in aef274d2685f

[verbose] Removing intermediate container aef274d2685f

[verbose]  ---> c3265bc5f3bd

[verbose] {"aux":{"ID":"sha256:c3265bc5f3bd8293da14b6723f7765d6b0ea2bdc1d295fec8dd447da26face99"}}
[verbose] Successfully built c3265bc5f3bd

[verbose] Successfully tagged exo-epickiwi-epickiwi-web:latest

[verbose] Updating serivce with following config:
[verbose] Service successfully updated!
[info] Deployment success!
Server response: {
  "message": "Deployment success!",
  "deployments": [
    {
      "ID": "wtgsu7i9icu163nqxfpefytpy",
      "Version": {
        "Index": 998
      },
      "CreatedAt": "2019-01-13T01:12:10.04393469Z",
      "UpdatedAt": "2019-01-16T22:28:48.62482359Z",
      "Spec": {
        "Name": "exo-epickiwi-epickiwi-web-405d3650",
        "Labels": {
          "exoframe.deployment": "exo-epickiwi-epickiwi-web-17ea3590",
          "exoframe.project": "exo-epickiwi-epickiwi-web",
          "exoframe.user": "epickiwi",
          "traefik.backend": "epickiwi.fr",
          "traefik.docker.network": "traefik-net",
          "traefik.enable": "true",
          "traefik.frontend.rule": "Host:epickiwi.fr",
          "traefik.port": "80"
        },
        "TaskTemplate": {
          "ContainerSpec": {
            "Image": "exo-epickiwi-epickiwi-web:latest",
            "Isolation": "default"
          },
          "Resources": {
            "Limits": {},
            "Reservations": {}
          },
          "RestartPolicy": {
            "Condition": "any",
            "MaxAttempts": 1
          },
          "Placement": {},
          "ForceUpdate": 1,
          "Runtime": "container"
        },
        "Mode": {
          "Replicated": {
            "Replicas": 1
          }
        },
        "UpdateConfig": {
          "Parallelism": 2,
          "Delay": 10000000000,
          "FailureAction": "pause",
          "MaxFailureRatio": 0,
          "Order": "start-first"
        },
        "Networks": [
          {
            "Target": "mn7ytzf056t0uplb0ievy57zr"
          }
        ]
      },
      "PreviousSpec": {
        "Name": "exo-epickiwi-epickiwi-web-405d3650",
        "Labels": {
          "exoframe.deployment": "exo-epickiwi-epickiwi-web-eb1a3f30",
          "exoframe.project": "exo-epickiwi-epickiwi-web",
          "exoframe.user": "epickiwi",
          "traefik.backend": "epickiwi.fr",
          "traefik.docker.network": "traefik-net",
          "traefik.enable": "true",
          "traefik.frontend.rule": "Host:epickiwi.fr",
          "traefik.port": "80"
        },
        "TaskTemplate": {
          "ContainerSpec": {
            "Image": "exo-epickiwi-epickiwi-web:latest",
            "Isolation": "default"
          },
          "Resources": {
            "Limits": {},
            "Reservations": {}
          },
          "RestartPolicy": {
            "Condition": "any",
            "MaxAttempts": 1
          },
          "Placement": {},
          "ForceUpdate": 1,
          "Runtime": "container"
        },
        "Mode": {
          "Replicated": {
            "Replicas": 1
          }
        },
        "UpdateConfig": {
          "Parallelism": 2,
          "Delay": 10000000000,
          "FailureAction": "pause",
          "MaxFailureRatio": 0,
          "Order": "start-first"
        },
        "Networks": [
          {
            "Target": "mn7ytzf056t0uplb0ievy57zr"
          }
        ]
      },
      "Endpoint": {
        "Spec": {},
        "VirtualIPs": [
          {
            "NetworkID": "mn7ytzf056t0uplb0ievy57zr",
            "Addr": "10.0.0.30/24"
          }
        ]
      }
    }
  ],
  "level": "info"
} 

Your project is now deployed as:

   ID                                       URL               Hostname   
   exo-epickiwi-epickiwi-web-405d3650       epickiwi.fr       Not set    
```

I'm confused about the value of `Spec.UpdateConfig.Delay: 10000000000`

**Comment by yamalight** [comment]
@EpicKiwi so, the update seems to go through correctly.
How are you validating that service wasn't updated? 🤔

`Spec.UpdateConfig.Delay: 10000000000` is an updated delay of 10s (in nanoseconds). This is needed so that old instance is not removed before new one is up (I assumed 10s would be enough for just about anything to start 🤔 )

**Comment by EpicKiwi** [comment]
If it's nanoseconds it's good. The service is not updated because the container isn't restared and the service still answer according to the old code.

**Comment by EpicKiwi** [comment]
I tried [node-test-server](https://github.com/exoframejs/exoframe-server/tree/master/test/fixtures/node-project) and it's updated well when `exiframe.json` doesn't contain a `domain` field. With a domain, the service isn't updating 10s-20s after executing the command. :thinking:

```json
{
  "name": "test-node-deploy",
  "domain": "ping.epickiwi.fr",
  "restart": "no"
}
```

**Comment by yamalight** [comment]
@EpicKiwi it does have `domain` in tests though 🤔  are you trying to change domain on update?

**Comment by EpicKiwi** [comment]
* If I change the domain and update : everything fine
* If I don't have a domain and update : everything fine
* If I have the same domain and update : image is uploaded and built but the running container isn't the new image

**Comment by yamalight** [comment]
@EpicKiwi you are deploying https://github.com/EpicKiwi/epickiwi-web right?
What changes are you making? I'll try to reproduce the bug using your project 🤔

**Comment by EpicKiwi** [comment]
Any change in the HTML : https://github.com/EpicKiwi/epickiwi-web/blob/master/src/views/index.html

But I have the same problem with your [test node project](https://github.com/exoframejs/exoframe-server/tree/master/test/fixtures/node-project)

**Comment by yamalight** [comment]
@EpicKiwi OK, will try to reproduce it once again 🤔 
just to be safe - what docker (daemon) version are you running?

**Comment by EpicKiwi** [comment]
```sh-session
$ docker --version
Docker version 18.09.1, build 4c52b90
```

**Comment by yamalight** [comment]
@EpicKiwi got it, thanks! will get back to you in the next couple of days

**Comment by yamalight** [comment]
@EpicKiwi just tried reproducing it with your project - also works just fine (changed header in `index.html`). 
Have you made any additional change to your docker maybe? 🤔

**Comment by EpicKiwi** [comment]
Thank you for your time, I will figure out.
I'll try to find why there is this kind of problem

**Comment by yamalight** [comment]
@EpicKiwi feel free to re-open this ticket (or open new ones) if you need more help 🤔
