### ISSUE TITLE
Create docs about deployments using Dockerfiles and docker-compose

### ISSUE THREAD

**Issue by mauriballes** [exoframejs/exoframe#200]
It will be a good idea because I have read all the issue to make a correct deployment using docker

**Comment by yamalight** [comment]
@mauriballes could you elaborate a bit on what was unclear for each type of deployments?

**Comment by mauriballes** [comment]
It would be a pleasure. For example, When I was doing a deploy using docker-compose.yml, for putting the domain in the labels of the service. If I only use a Dockerfile, I don't have problem, but things like traefik labels it's important to mentions.

**Comment by mauriballes** [comment]
In your articles in medium only find a example with static page, so It's a good idea have more example with your tool. I personally like it and maybe you can develop a Wiki or a start guide with all the deployment methods

**Comment by yamalight** [comment]
@mauriballes cool. closing this one then
