### ISSUE TITLE
Expose deployment labels as environment variables

### ISSUE THREAD

**Issue by larsthorup** [exoframejs/exoframe#212]
We are using exoframe to create ad-hoc sandbox environments for testing, and are very happy with it so far! However, the sandbox server process need to generate URLs to itself, and I have not found a way for the process to access the deployment-id. Each sandbox gets a new random deployment-id which looks like this:

* exo-lars-tz-d3bf77e1

so the process needs to generate a URL that looks like this: 

* exo-lars-tz-d3bf77e1.exo.triggerz.io

How can we accomplish that?

**Comment by yamalight** [comment]
@larsthorup you need to specify `baseDomain: .exo.triggerz.io` in your server config. Then any deployments that don't have domain explicitly set will be autoset to `${deployment-id}${baseDomain}` - so, e.g. deployment with id `exo-lars-tz-d3bf77e1` will be assigned domain `exo-lars-tz-d3bf77e1.exo.triggerz.io` which sounds like exactly what you want

**Comment by yamalight** [comment]
Aaaand I've totally read that incorrectly 🤦‍♂️

**Comment by yamalight** [comment]
I guess that it would indeed be a good idea to expose those values as environmental variables 🤔

**Comment by yamalight** [comment]
Will ship it with v4.0 in the next couple of days 🤔

**Comment by yamalight** [comment]
Done and ready to ship.

**Comment by larsthorup** [comment]
Very impressed with the extraordinarily quick handling of this issue: implemented within the hour, released within the day, the feature just works, and upgrading to exoframe@4 also just worked. Thank you so much!
