### ISSUE TITLE
Allow for alternative config file to be used

### ISSUE THREAD

**Issue by klirix** [exoframejs/exoframe#215]
Currently here is no a way to feed exoframe an alternative config file (example use case: staging environment)

It should be a pretty easy feature to implement, so I can provide a pr for this.

**Comment by yamalight** [comment]
@klirix would be totally up for a PR.
Although I think it'd be a bit tricky to implement.
I guess the easiest way would be to do this purely on client. Something like this would probably work:
- User passes `exoframe --config file.json`
- Exoframe CLI ignores original `exoframe.json` during packing
- Exoframe CLI renames `file.json` to `exoframe.json` during packing

**Comment by klirix** [comment]
I implemented it using first option providing —config (-c) option during
deployment. I’ll work on some edge cases (like if the config file does not
exist) and open a pr for this issue.

**Comment by WNemencha** [comment]
Hey @klirix,

Any progress on that feature? Looks like an essential feature to me, I'm willing to give help if needed. :p

**Comment by klirix** [comment]
@WNemencha Just pushed a draft PR(#225 ) which I was using, without the tests atm, feel free to add them

**Comment by yamalight** [comment]
Done and ready to ship.
