### ISSUE TITLE
exoframe v4.0.0 + digitalocean + node

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#217]
Hi, thanks for cool tool. So far so good.
I got issue not sure why and who is guilty. Deployment went without any problems, but I noticed that deployed version is not updated. Every time I refresh page I got different deployed version
![image](https://user-images.githubusercontent.com/468006/55154601-e22e3c00-515d-11e9-975f-a6f74ac3751f.png)
It is reproducible here http://webcomponents.die.lt/

![Screen record from 2019-03-28 13 47 05](https://user-images.githubusercontent.com/468006/55155551-57027580-5160-11e9-82e0-a5e33a6b6b1e.gif)

**Comment by FDiskas** [comment]
exoframe.json
```json
{
  "name": "webcomponents",
  "restart": "on-failure:2",
  "domain": "webcomponents.die.lt",
  "rateLimit": {
    "period": "1s",
    "average": 1,
    "burst": 5
  },
  "hostname": "die.lt",
  "template": "node"
}
```

**Comment by yamalight** [comment]
I am assuming you are running `exoframe` for deployment.
Doing so will result in new instance being deployed every time. You can check that by running `exoframe ls`.
If you want to replace existing instance - you need to add update flag. So, `exoframe -u`.

**Comment by FDiskas** [comment]
probably `-u` flag should be default :/ Thanks
