### ISSUE TITLE
Allow non-interactive config modification

### ISSUE THREAD

**Issue by paulkre** [exoframejs/exoframe#218]
I am very happy with exoframe ❤️. There is just one thing I would like to change:

I don't want to specify the project's domain in the exoframe.json file of the repository. I would like to specify it in the deployment process during ci. The domain should be parsed as an environment variable like the endpoint and the deployment token. This is important because the repository should not be dependent on the availability of the domain. Also other people might want to host the project on different or even multiple domains. So it would be great if you could specify the domain in the exoframe deploy method like this:

```
exoframe endpoint $EXOFRAME_ENDPOINT
exoframe -u -t $EXOFRAME_TOKEN --domain $DOMAIN
```

**Comment by yamalight** [comment]
@paulkre thanks for suggestion.
I don't think adding it to deployment is a good idea as it would require significant code changes.
I do think that having a way to modify config in a non-interactive way is useful though.
I'm thinking of having something like: `exoframe config --domain $DOMAIN`
Then you could easily modify it before running deploy in CI envs.

**Comment by paulkre** [comment]
@yamalight sounds good. It won't be easy to specify advanced parameters this way (like rateLimit) so modifying an existing config file sounds like a good solution.

**Comment by SeaLife** [comment]
I made some local changes to target this issue...

Are you guys fine by defining a argument to indicate "non-interactive" mode?

I've made the following scenario working so far:


```
exoframe config --non-interactive --domain test.example.com --project test1234 --name testProject
```

`--non-interactive` can be shortcutted by `-x`

Regards
SeaLife

**Comment by yamalight** [comment]
@SeaLife I don't think `--non-interactive` flag is needed. As long as at least one flag is passed - it should work as non-interactive mode and just write given data to config 🤔

**Comment by SeaLife** [comment]
Okay, will dig into this and try this out... :) 
Will mostly create a PR for this too

**Comment by SeaLife** [comment]
Example output:

```
➜  exoframe-test master ✗ node ../exoframe/index.js config --domain exoframe-test1.r3ktm8.de --hostname test --name projectxyz
Config already exists! Editing..
Mode changed to non-interactive
Setting domain to exoframe-test1.r3ktm8.de
Setting name to projectxyz
Setting hostname to test
Config created!


➜  exoframe-test master ✗ cat exoframe.json 
{
  "name": "projectxyz",
  "restart": "always",
  "domain": "exoframe-test1.r3ktm8.de",
  "project": "exoframe-test",
  "hostname": "test"
}%
```

Something like this?

**Comment by yamalight** [comment]
@SeaLife yep, this looks perfect!

**Comment by SeaLife** [comment]
So, i created this for the simple fields that just contains strings...
This should fit the most needs in CI environment i think... (At least for my use cases)

**Comment by yamalight** [comment]
Done and ready to ship!
