### ISSUE TITLE
Clean unused code in the server

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#221]
Argument is passing

https://github.com/exoframejs/exoframe-server/blob/275b74c6d515e7ffe2cc9ea00ee4e2af910c06e7/src/routes/update.js#L58

But here is nothing about any argument

https://github.com/exoframejs/exoframe-server/blob/275b74c6d515e7ffe2cc9ea00ee4e2af910c06e7/src/docker/init.js#L37

**Comment by yamalight** [comment]
Good catch, will clean it up at some point.

**Comment by yamalight** [comment]
Done and ready to ship.
