### ISSUE TITLE
Docker-compose project fails to update

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#223]
1. Deleted all contents from `.exoframe/deploying`
1. on host run `exoframe`
1. everything succeeded.
1. folder `.exoframe/deploying` is still empty
1. on host `exoframe -u` got error `No such container: 6c1798c0....`

Reproduce: [fail.zip](https://github.com/exoframejs/exoframe/files/3027013/fail.zip)

**Comment by yamalight** [comment]
Thanks for reporting. Will investigate once I have time

**Comment by FDiskas** [comment]
Just a note what I was trying to todo: :sheep:
1. at https://api.rank.lt I would run strapi endpoint for rest api (fail)
1. at https://api.rank.lt/admin to have access to headles cms (fail)
1. at  https://rank.lt run simple static website (works)
1. mongodb up and running (works)
1. mongo-express temproray accessable at http://rank.lt:8081 (works)

**Comment by yamalight** [comment]
Was able to repro this. Seems to be related to re-use of existing containers by docker-compose.
Will try to figure out how to work around this 🤔

**Comment by FDiskas** [comment]
What if rebuild flag pass to the process?

**Comment by yamalight** [comment]
That won't help. 
Current issue happens because execution of `docker-compose up` re-uses existing containers (databases in this case) and Exoframe tries to remove them expecting new instances to be started.

**Comment by FDiskas** [comment]
Add additional question during deployment?
Do you want to destroy curently running instances?

**Comment by yamalight** [comment]
Question won't help since this is an issue on server.
We _need_ to destroy old instances, otherwise you'll end up having the same service deployed twice - which is not what we want

**Comment by yamalight** [comment]
Should be fixed in Exoframe-server 5.0.3. Feel free to re-open if that's not the case.
