### ISSUE TITLE
Dockerfile broken (compose install fails)

### ISSUE THREAD

**Issue by Aeolun** [exoframejs/exoframe#226]
Is the Dockerfile currently displayed on the project `develop` branch out of date?

I've had to add `gcc python2-dev libffi-dev openssl-dev` to `apk install`, and it's finally passing that stage in the dockerfile.

**Comment by yamalight** [comment]
Dockerfile is up to date and compiles fine. Same one is used in the `master` for stable releases.
You can find pre-built images using that file (for both dev and master) on [docker hub](https://hub.docker.com/r/exoframe/server).

What was the error you were getting?

**Comment by Aeolun** [comment]
Initially I got this error. 

```
error: command 'gcc' failed with exit status 1
  
      ----------------------------------------
  Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7JdKlV/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-q1XKog/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-Pwa9wP --compile" failed with error code 1 in /tmp/pip-install-7JdKlV/cffi/
  
  ----------------------------------------
Command "/usr/bin/python2 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-Pwa9wP --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "cffi>=1.1; python_implementation != 'PyPy'"" failed with error code 1 in None
The command '/bin/sh -c apk update && apk add --no-cache libstdc++ libgcc py-pip yarn && pip install docker-compose' returned a non-zero code: 1
ERROR: Job failed: exit code 1
```

After that variations of the same until I added all above packages. Apparently it needed headers that were not available by default in the base image?

I’m not sure how that would be possible if it works for you and we are building from the same image/file though 😮

Let me try building it locally instead of on CI, and see how that goes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yamalight** [comment]
@Aeolun this is quite weird, never seen those errors.
The images on docker hub are built automatically using Travis-CI, you can check the logs [here](https://www.travis-ci.org/exoframejs/exoframe-server/builds/513709203) and [here](https://www.travis-ci.org/exoframejs/exoframe-server/builds/515661282) if you are interested.

**Comment by yamalight** [comment]
Huh, now that's interesting. `docker build` in travis does fail 🤔

**Comment by yamalight** [comment]
It seems to error out, but still produce the image. I am so confused right now

**Comment by yamalight** [comment]
Right, looks like I was hitting cache locally - that's why it worked for me. 
This is indeed a bug.

**Comment by yamalight** [comment]
There's an official [compose docker image](https://hub.docker.com/r/docker/compose/tags) that's [based off](https://github.com/docker/compose/blob/master/Dockerfile.run) of alpine. Might be a good idea to just use it 🤔

**Comment by yamalight** [comment]
Should be fixed now, waiting on CI..

**Comment by yamalight** [comment]
Yep, fixed now. Thanks for catching this 😄
