### ISSUE TITLE
http2

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#228]
It would be nice to have http2 by default.

**Comment by yamalight** [comment]
Traefik already supports HTTP2

**Comment by yamalight** [comment]
To elaborate - HTTP2 will work if you enable TLS (e.g. letsecrypt)

**Comment by FDiskas** [comment]
Thanks
![image](https://user-images.githubusercontent.com/468006/56148637-63d1f680-5fb3-11e9-81b1-08e586e8f6ec.png)
