### ISSUE TITLE
Use consistent templates names

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#229]
Currently template names are confused in some cases like:

https://github.com/exoframejs/exoframe-server/blob/275b74c6d515e7ffe2cc9ea00ee4e2af910c06e7/src/docker/templates/nginx.js#L10-L11

I would suggest or symbolic names or real names like ngnix, node, and so on. Also in documentation it's mentioned that core templates are "ngnix,..." but actual name is "static"

**Comment by yamalight** [comment]
That's a good catch. It should be called `static` everywhere. PRs welcome!

**Comment by yamalight** [comment]
Done and ready to ship
