### ISSUE TITLE
Noninteractive secret creation

### ISSUE THREAD

**Issue by flobaader** [exoframejs/exoframe#232]
Hi,

is it currently possible to create a secret in a non-interactive way, e.g. in CI scripts?

In the feature proposal #184 the suggested command is `exoframe secret add secret-name secret-value`. I also tried `exoframe secret new secret-name secret-value` without success.

Thank you in advance!

**Comment by yamalight** [comment]
@flobaader currently that's not possible, but PR is more than welcome!

**Comment by yamalight** [comment]
Done and ready to ship
