### ISSUE TITLE
Set traefik.enable tag on containers

### ISSUE THREAD

**Issue by flobaader** [exoframejs/exoframe#236]
Hi,

I configured my own traefik instance and set

```
[docker]
exposedbydefault=false
```

to have a fine-grained control on what is exposed. 

Could you please add the label `traefik.enable: true` to all containers created by exoframe?
Then the containers will definitely be exposed by traefik.

**Comment by yamalight** [comment]
@flobaader this is something that's already being set in the latest version (see https://github.com/exoframejs/exoframe-server/pull/15 )

**Comment by flobaader** [comment]
Oh okay, thank you very much!
