### ISSUE TITLE
Allow alternative ports

### ISSUE THREAD

**Issue by willvincent** [exoframejs/exoframe#237]
Traefik is able to properly route whatever port necessary on a backend service container by applying the label `traefik.port` to the container.

I've been doing this (manually) for a couple years on my personal server, ie:

```
"traefik.docker.network": "http_network",
"traefik.enable": "true",
"traefik.frontend.rule": "Host:something.example.com",
"traefik.port": "3333"
```

I propose updating the various templates to either accept an explicit `port` parameter in the config file and override the default port 80 with it if set.

Quick look at the server code, for node projects, it looks like the changes ought to be minimal..

Accept `config` which is already passed to the executeTemplate method.
Determine the appropriate port and pass that to  `nodeDockerfile()`:
```
    const dockerfile = nodeDockerfile({
      hasYarn: filesList.includes('yarn.lock'),
      hasLock: filesList.includes('package-lock.json'),
      port: config.port ? config.port : 80,
    });
```

and similarly, update the nodeDockerfile method to make use of that port value:
```
const nodeDockerfile = ({hasYarn, hasLock, port}) =>
  `FROM node:latest

# create folder and set it as workdir
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# copy package and yarn files to cache deps install
${yarnOrNpm({hasYarn, hasLock})}

# copy app itself
COPY . /usr/src/app

EXPOSE ${port}
LABEL traefik.port=${port}

CMD ["npm", "start"]
`;
```

Probably would make sense to also support additional arbitrary labels here too...

Haven't had any luck getting a properly functioning test env. setup locally, so not confident in the changes to submit a PR.. suspect changes would be similar for all templates though

**Comment by willvincent** [comment]
Guess this is sort of related to #121

**Comment by yamalight** [comment]
@willvincent exoframe defaults to port 80, but you can change this by passing traefik labels via config (see [project config docs](https://github.com/exoframejs/exoframe/blob/master/docs/Basics.md#project-config-file) for more info)

**Comment by willvincent** [comment]
The node template (at least) is hardcoded to `EXPOSE 80` though..

**Comment by yamalight** [comment]
I'd suggest using custom Dockerfile if you need this level of customization 🤔

**Comment by yamalight** [comment]
I'll close this due to inactivity. Feel free to re-open if needed.
