### ISSUE TITLE
Allow running `exoframe rm` with name or domain

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#245]
Currently `exoframe rm` allows removing either via deployment ID or configured `project`.
It would be great to have an ability to remove deployments using either `name` or `domain` from config as well.

**Comment by SeaLife** [comment]
Made a PR for this, see https://github.com/exoframejs/exoframe-server/pull/24

**Comment by yamalight** [comment]
Ready to ship. Thank you for your work! ❤️
