### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by unzchf** [exoframejs/exoframe#251]
Hi there,

I've installed Exoframe on my VPS successfully, but I can't get Let's Encrypt working. This causes my deployment to only work over HTTP, but refuse HTTPS connections. I've previously used HSTS on the same domain, so my website is completely unreachable for normal browsers.

Below is my `/root/.exoframe/server.config.yml`:
```yml
letsencrypt: true
letsencryptEmail: [secret]
```

After creating the configuration file and adding those settings, I did the following:
```sh
$ docker ps -a
$ docker stop [traefik-container-id]
$ docker rm [traefik-container-id]
$ docker restart [exoframe-server-id]
$ docker logs [exoframe-server-id]
```

This is the output from the last command above:
```sh
[exoframe-server] › ℹ  info      Initializing docker services...
[exoframe-server] › ℹ  info      Exoframe network exoframe does not exists, creating...
[exoframe-server] › ℹ  info      No traefik image found, pulling..
[exoframe-server] › ℹ  info      Traefik instance started..
[exoframe-server] › ℹ  info      Server running at: 8080
[exoframe-server] › ℹ  info      Initializing docker services...
[exoframe-server] › ℹ  info      Traefik instance started..
[exoframe-server] › ℹ  info      Server running at: 8080
[exoframe-server] › ℹ  info      Initializing docker services...
[exoframe-server] › ℹ  info      Traefik already running, docker init done!
[exoframe-server] › ℹ  info      Server running at: 8080
[exoframe-server] › ℹ  info      Initializing docker services...
[exoframe-server] › ℹ  info      Traefik instance started..
[exoframe-server] › ℹ  info      Server running at: 8080
```

When I try to access my deployment URL over HTTPS, I get connection refused on port 443.

I tried removing my deployment and deploying it again, and looking at the deployment logs where my Node.js Express application is connecting to port 80 on localhost just fine.

I've tried looking in the Traefik logs using `docker logs [traefik-container-id]`, but it's empty.

Thanks for any help!

**Comment by unzchf** [comment]
I'm not sure if this is important, but I had no `~/.exoframe/server.config.yml` file created by default, so I had to manually create it. Thanks!

**Comment by unzchf** [comment]
```sh
$ exoframe ls
1 deployments found on [secret]:

> Normal deployments:

   ID                           URL                Hostname       Status        Type        
   [secret]                  [secret]             Not set        running       Container
```

**Comment by yamalight** [comment]
@unzchf can you please share `docker inspect exoframe-traefik` info?
do you have a firewall set up? is port 443 allowed for use?

**Comment by yamalight** [comment]
It's also weird that server didn't create config. What command did you use to start the server?

**Comment by unzchf** [comment]
Hi there,

I'll share the `docker inspect exoframe-traefik` info ASAP. Meanwhile, I can quickly answer your other questions:

Yes, I have a firewall setup (ufw) which allows 443/tcp. I used the following command to setup my Exoframe server:
```sh
$ docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /path/to/exoframe-folder:/root/.exoframe \
  -v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
  -e EXO_PRIVATE_KEY=your_private_key \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:exoframe.[secret] \
  --restart always \
  --name exoframe-server \
  exoframe/server
```

I noticed now that I didn't change the `EXO_PRIVATE_KEY` environment variable from "your_private_key" - not sure if that would cause problems.

Thanks!

**Comment by yamalight** [comment]
The most important question here is - have you changed volume paths (on the left side)?
```
-v /path/to/exoframe-folder:/root/.exoframe \
-v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
```
Those should point to correct locations otherwise there'll be issues 🤔

**Comment by unzchf** [comment]
Oh! 👀 There we have it, I'll reinstall Exoframe and change the volume paths. Completely didn't see those, sorry!

**Comment by unzchf** [comment]
Issue is most likely solved then! Thanks, I'll open a new issue if that doesn't solve my problem <3

**Comment by yamalight** [comment]
@unzchf sure, would be happy to help!
