### ISSUE TITLE
Allow assigning custom certs through CLI

### ISSUE THREAD

**Issue by ghost** [exoframejs/exoframe#252]
Hi there,

Just a little feature request: It'd be very cool to allow assigning custom certificates using the Exoframe CLI to each of your deployments.

This would be perfect if you intend to host multiple sites behind Cloudflare, which acts as a proxy between your Exoframe server and the user accessing the site.

At the moment, you need to disable the proxying feature (turning off the orange cloud) for the DNS record pointing to Exoframe in order for Let's Encrypt to generate an origin cert.

Cloudflare offers generating free origin certificates only trusted by Cloudflare, valid for up to 15 years, from the dashboard.

If Exoframe allowed providing these certificate files when deploying a site, Cloudflare users would not have to give up  all performance and security features provided by Cloudflare.

Most important to me is to not expose my origin server IP address on my Exoframe deployments.

Thanks for an amazing tool!

**Comment by unzchf** [comment]
[https://zeit.co/blog/now-certs](Example of how the commands could look like).

**Comment by yamalight** [comment]
You can achieve this by configuring traefik manually (see [their docs](https://docs.traefik.io/user-guide/examples/#http-https-with-sni)).
Exoframe currently executes traefik with config as flags passed in (which is not as flexible as a file config), but you can start your own traefik first and then tell exoframe to use it (see `traefikName` prop in [server config](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md)).
There is a ticket (https://github.com/exoframejs/exoframe/issues/139) already to actually use traefik config so it can be easily tweaked, but I haven't gotten around to implementing it yet.

**Comment by unzchf** [comment]
All right, thanks!

**Comment by yamalight** [comment]
I'll close this due to inactivity. Feel free to re-open if needed.
