### ISSUE TITLE
Server with existing Traefik container

### ISSUE THREAD

**Issue by victorberland** [exoframejs/exoframe#258]
So I'm trying to set up Exoframe on a VPS, but I'm having issues getting the client to login to the server. I used
```
docker run -d \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /opt/exoframe:/root/.exoframe \
  -v /home/user/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro \
  -e EXO_PRIVATE_KEY=mykey \
  --label traefik.backend=exoframe-server \
  --label traefik.frontend.rule=Host:v.domain.net \
  --label traefik.port=8080 \
  --label traefik.enable=true \
  --restart always \
  --name exoframe-server \
  exoframe/server
```
I added the traefik enable and traefik port labels in order to try to get Traefik to maybe point my domain correctly, but I keep getting 502 Bad Gateway. Does the client connect via HTTP or SSH?

Any clues to help me in the right direction would be appreciated 🙏

**Comment by yamalight** [comment]
@victorberland client works over HTTP. you can test the server by accessing your host (`v.domain.net`) in browser.
If that doesn't work - please check the logs from traefik and exoframe server

**Comment by victorberland** [comment]
Seems like the issue was related to Traefik not at all being able to talk with Exoframe. Got it working now 👍
