### ISSUE TITLE
Migrate to Traefik v2.0 once it's been released

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#263]
Traefik v2.0 is releasing [soon-ish](https://twitter.com/traefik/status/1166291965119520770).
We need to migrate to it at some point.
~For now we should also lock used traefik version to v1.x~

**Comment by yamalight** [comment]
Exoframe-server v5.0.4 now has Traefik pinned to v1.7.x

**Comment by yamalight** [comment]
v2.0 has been release. Here's a migration guide: https://docs.traefik.io/v2.0/migration/v1-to-v2/

**Comment by yamalight** [comment]
This is _a lot_ of work. They've fundamentally changed how some things work, so some parts of Exoframe would have to be entirely rewritten to fit that (e.g. compression is no longer enabled globally, but needs to be set per-serivce as middleware.
I am not convinced it's worth it at this point.

**Comment by alexanderadam** [comment]
> I am not convinced it's worth it at this point.

So you would rather stick to 1.7 until 1.7 is getting no security patches anymore? :thinking:

**Comment by yamalight** [comment]
@alexanderadam I have actually started migration (or at least attempting to), but boy this is not easy and I don't know how long it'll take

**Comment by yamalight** [comment]
Server now supports Traefik v2.0. Still need to update CLI, swarm plugin and rest of the stuff.
There are some trade-offs, breaking changes and no simple way to migrate old deployments (they'll need to be re-deployed).

**Comment by alexanderadam** [comment]
Wow, either you have a time machine or you are incredible fast!
Thank you for your fast response. :pray: 

Would you consider the dev version stable enough for new production deployments?

**Comment by yamalight** [comment]
@alexanderadam dev version is probably not yet stable enough for production - I might've missed something related to traefik there, so it still needs additional testing (I'll likely do RC first, test it on my servers, only then release stable).

On schedule - if I have enough time to work on it - I'd say ~end of next week or so.

**Comment by alexanderadam** [comment]
Wooah! I guess you know this anyway but just to make this clear: this is _great_ news! Thank you!

**Comment by SeaLife** [comment]
I thought on starting the migration on my own cuz we recently switched to Traefik 2.0...

Its mostly all done by using labels and exoframe-server is also using these labels...
It should be easy to adapt the labels to the new one...

But the old deployments wont work for sure :)

I'll take a look at the dev version

**Comment by yamalight** [comment]
@SeaLife second pair of eyes is more than welcome :)
I've actually finished majority of the ground work in dev branch, it just needs some double-checking, documentation and all that stuff.

**Comment by yamalight** [comment]
Last bits to do:

- [ ] Make sure letsencrypt correctly issues certs
- [ ] Document migration path

Once this works, the migration is basically done.

**Comment by alexanderadam** [comment]
You are incredible! Thank you for those great news, Tim!

**Comment by yamalight** [comment]
Done and shipped in v6.0
