### ISSUE TITLE
`exoframe --update` breaks static (Nginx) deployments

### ISSUE THREAD

**Issue by sgoll** [exoframejs/exoframe#265]
When running deployments with the option `--update` (in order to update an existing deployment), static deployments (using template `static`, i.e. Nginx) show only the blank Nginx welcome page instead of the actual deployment contents.

Steps to reproduce:

1. Set up deployment with `"template": "static"` in `exoframe.json`
2. Run updating deployment with `exoframe --update …`

Expected outcome:

It should not matter whether `--update` is given or not, the static deployment should show the actual contents instead of the Nginx welcome page.

Exoframe version:

`5.2.0`

**Comment by yamalight** [comment]
@sgoll could you please share an example project that reproduces this?

**Comment by sgoll** [comment]
@yamalight Here you go: https://github.com/sgoll/exoframe-test

The problem happens only when a deployment path is specified on the command-line. In this case, the path resolution for `exoframe.json` differs between regular and `--update` deployment runs.

In the reproduction repository, you can see the following:

- `npm run deploy` creates a blank `exoframe.json` in `public/`
- `npm run deploy-update` creates a blank `exoframe.json` in `./`

**Comment by yamalight** [comment]
@sgoll yep, that's a bug! thanks for catching it, fix incoming in a few mins.

**Comment by yamalight** [comment]
@sgoll v5.2.1 should be up on npm now with a fix. Feel free to re-open the issue if it still persists!
