### ISSUE TITLE
traefik error: field not found, node: accesslogsfile

### ISSUE THREAD

**Issue by larsthorup** [exoframejs/exoframe#267]
I just attempted to upgrade exoframe to latest versions using `exoframe update` providing this output:

    Exoframe Server:
      current: 5.0.4
      latest: 5.0.4
    Traefik:
      current: v1.7.14
      latest: v1.7.18

The update failed with this error:

    TypeError: Cannot read property 'body' of undefined

And after this traefik is no longer running on the server, also not after rebooting the server.

It appears that the container running traefik:latest fails to start:

    $ sudo docker container ls --all | grep traefik
    a6199d2c8f14        traefik:latest               "/entrypoint.sh -c /…"   4 minutes ago       Exited (1) 4 minutes ago

The log file from the traefik:latest container shows:

    $ sudo docker logs a6199d2c8f14
    2019/10/05 13:57:31 command traefik error: failed to decode configuration from flags: field not found, node: accesslogsfile
    2019/10/05 13:57:37 command traefik error: failed to decode configuration from flags: field not found, node: accesslogsfile
    2019/10/05 13:57:42 command traefik error: failed to decode configuration from flags: field not found, node: accesslogsfile

Note, that we have been running exoframe on this server since December 2018.

How do I get traefik up and running again?

Thanks!

**Comment by yamalight** [comment]
@larsthorup this is because traefik was update to v2.0 that is not yet compatible with Exoframe.
Please edit your exoframe server config and lock `traefikImage` to `traefik:v1.7`, then kill old traefik and restart Exoframe - it should start working after that

**Comment by larsthorup** [comment]
Thank you @yamalight for the fast and helpful response! For the record I did these steps:

In ~/.exoframe/server.config.yml I updated the line to this:

    traefikImage: 'traefik:v1.7'

And then rebooted the server. And then everything appears to work as expected.

Thanks again - closing the issue.

**Comment by misaon** [comment]
Is Traefik 2 supported in Swarm mode today?

**Comment by yamalight** [comment]
@misaon it should be, yeah
