### ISSUE TITLE
traefik/acme mounts to /root/.exoframe instead of /path/to/exoframe-folder

### ISSUE THREAD

**Issue by VojGin** [exoframejs/exoframe#268]
System: macOS Catalina
Running on: macOS Docker Desktop installation

Issue:
When exoframe-server initiates traefik container, it binds the traefik/acme folder to the **/root/.exoframe** (root inner mount of exoframe-server) instead of the **/path/to/exoframe-folder** specified by docker run

```
docker run -d \
  ...
  -v /path/to/exoframe-folder:/root/.exoframe \
  ...
```

traefik config:
<img width="1200" alt="Screenshot 2019-10-15 at 10 08 28" src="https://user-images.githubusercontent.com/5146396/66813767-ae6a0680-ef35-11e9-9990-744599420f5a.png">

exoframe-server config:
<img width="1200" alt="Screenshot 2019-10-15 at 10 21 08" src="https://user-images.githubusercontent.com/5146396/66813777-b1fd8d80-ef35-11e9-8fc0-937705330075.png">

**exoframe-server/src/docker/init.js**
```
line 14-15:
// config vars
const baseFolder = path.join(os.homedir(), '.exoframe');

...

line 53-59:
// build acme path
const acmePath = path.join(baseFolder, 'traefik', 'acme');
try {
  fs.statSync(acmePath);
} catch (e) {
  mkdirp.sync(acmePath);
}
```

The ``os.homedir()`` is bound to a the **inner environment** of the exoframe-server container.

No certificates are saved so I burned through letsencrypt rate-limit in a day when the server restarted twice. 😄

Tried to hotfix it by a symbolink link, but macOS says: ``/root: Read-only file system``

Not sure if it's possible to read the mounts from the inner environment and use it tho.

**Comment by yamalight** [comment]
This seems like an issue with volumes. Volumes are not something Exoframe controls in any way - it just uses `os.homedir()` as you've correctly noted. 
This likely has something to do with Docker for Mac and (I'm guessing) Catalina upgrade.

**Comment by VojGin** [comment]
Yeah I know, it definitely worked for me on debian for more than a year and (probably) on previous macOS too.

Just can't think of a suitable fix now.
If you got any idea, let me know and I can test it, create PR...

**Comment by VojGin** [comment]
Fixed for now by manually remounting.
But it is not a persistent fix and anyone running exoframe on macOS server may face the same issue.

**Comment by yamalight** [comment]
I really don't think this is fixable from Exoframe side - it seems like a docker for mac bug to be honest 🤔

**Comment by VojGin** [comment]
You may put it somewhere in the docs for anyone else going through the same hassle trying to find out why I burned through acme rate-limit in just a few hours and now locked for one week from certificates.

Or perhaps archive of this issue will do.

**Comment by yamalight** [comment]
After seeing PR - the problem finally "clicked" for me.
I think the best solution would be to use the current code + try to get volume from exoframe-server container if it's running. This would allow to run exoframe-server both with and without docker without any issues.

**Comment by yamalight** [comment]
Done and ready to ship.
