### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by bureson** [exoframejs/exoframe#276]
As a part of regular chores we tried to update our exoframe server instance to the latest version, but upon running `exoframe update`, the console returns the following output, gets stuck and get only be killed from the task manager.

```
‼ Updates available!

Exoframe Server:
  current: 5.0.4
  latest: 6.0.2

Traefik:
  current: v1.7.18
  latest: v1.7.20
```
I'm not sure how to proceed from this point or how debug in order to be able to provide more information.

**Comment by yamalight** [comment]
@bureson update from v5 to v6 unfortunately won't work - there's too many breaking changes.
you need to [migrate manually](https://github.com/exoframejs/exoframe/blob/master/CHANGELOG.md#migrating-to-v60) as stated in changelog

**Comment by yamalight** [comment]
closing this as stale. feel free to re-open if needed.
