### ISSUE TITLE
Setup issues (letsencrypt/https)

### ISSUE THREAD

**Issue by zgec** [exoframejs/exoframe#277]
First, thanks for this amazing project! I wish I discovered it earlier.

I just wanted to report an issue on a brand new server setup of exoframe.

Did it on a fresh install of:
Ubuntu Server 18.04

I installed docker and followed guide at:
https://github.com/exoframejs/exoframe/blob/master/docs/ServerInstallation.md
(I left letsencrypt flag on)

After running that command, I went to exoframe CLI and ran:
exoframe endoint http://myserver.example.com
and then exoframe login

However, then, I experienced:
`Error logging in! Error getting login request phrase. Make sure your endpoint is correct! HTTPError: Response code 404 (Not Found)`

When going in browser to: http://myserver.example.com/ I saw a "404 page not found"
While **https://**myserver.example.com/ would result in a timeout.

---

**How I solved it**
- went to: exoframe-folder/server.config.yml
- enabled letsencrypt, letsencryptEmail, baseDomain, swarm (false)
- stopped, removed containers
- reran the docker run command from instructions (this time with the exoframe folder present, with changed config)
- logged in successfully through CLI using **https://**myserver.example.com/

**Comment by yamalight** [comment]
@keymaker91 as the docs [state](https://github.com/exoframejs/exoframe/blob/master/docs/ServerConfiguration.md) - you need to kill / remove traefik after enabling letsencrypt (so that exoframe can restart it with correct flags). I'm guessing that's where the issue were, so stopping / removing traefik, and then restarting exoframe-server would be enough 😅

**Comment by keymaker91** [comment]
Right, that last part - solution - really felt like a hack :)

I guess what is missing in the docs for server installation, is a notice that you should enable letsencrypt manually after running that docker run command if you want to use exoframe through https?

**Comment by yamalight** [comment]
@keymaker91 exoframe definitely needs better docs, can't argue with this 😅 
my plan was to rework the docs once I build a website (#259), couldn't find time to that yet though 🤔

**Comment by yamalight** [comment]
Closing this, will address the issue once I start working on the website and overhauling docs.
