### ISSUE TITLE
Server CI: Only deploy to docker hub on develop branch and on tags

### ISSUE THREAD

**Issue by anbraten** [exoframejs/exoframe#282]
Currently the docker build and login is executed on every pull request and branch. I would suggest to only build on the main repo on tags and develop like it is done with npm builds. 
Maybe using Github actions would be nice as well.

**Comment by yamalight** [comment]
I've been wanting to migrate to github actions for some time now - travis has been acting very quirky as of late.
Just didn't have enough time to dive into that :(
