### ISSUE TITLE
Default ignores/.exoframeignore doesn't work on Windows

### ISSUE THREAD

**Issue by HTLFabian** [exoframejs/exoframe#284]
I was wondering why the deployment process always takes so long, and then I found out node_modules wasn't excluded. I tracked down where the issue resides, and here is the cause:
https://github.com/exoframejs/exoframe/blob/0e4feb77955217625a9a65dde70bcfc880791d2b/src/commands/deploy.js#L186
It only replaces the workdir followed by a `/`, but on Windows it won't do anything because of the _best_ feature Windows has to offer (`\` in the path).

**Comment by yamalight** [comment]
@HTLFabian right, I guess it'd be better to use `path` package for that stuff to make it cross-platform 🤔 
I'll look into it once I have some free time. PR is very welcome :)

**Comment by yamalight** [comment]
Ready for release in the next update thanks to @FDiskas
