### ISSUE TITLE
Exoframe functions

### ISSUE THREAD

**Issue by kennetpostigo** [exoframejs/exoframe#285]
Hey, 

Was looking at some of the documentation for functions and noticed that `http` functions take `event` and `context` params. I was pretty confused by that, wondering why it doesn't take `req` and `res` params that most lambda functions typically take.

**Comment by yamalight** [comment]
@kennetpostigo because there's a way to have custom triggers that provide custom `event` and `context`, see [this example](https://github.com/exoframejs/exoframe/blob/master/docs/Functions.md#simple-trigger-function)

**Comment by kennetpostigo** [comment]
@yamalight Just some context, my team is looking to move off of now to a self hosted solution like exoframe, however all our infrastructure uses [micro](https://github.com/zeit/micro).

All of our lambdas, servers, and libraries on the server are centered around it. Is there anyway I can keep using micro with exoframe long-running servers and exoframe functions?

I don't mind doing some ground work maybe creating a fork based off the exoframe functions, but i'm unsure of how to use that fork with exoframe.

**Comment by yamalight** [comment]
Simplest way would be to run them as simple deployments (so just dockerized node instances).

Another way would be to extend exoframe plugins to allow working with HTTP, so you could create a fork of `exoframe-faas` and tweak it to work with micro and then use it as a plugin (should be relatively straightforward task).

But unless you really want to keep running everything as functions, I'd recommend going with the first option - you'll get more control over deployments this way

**Comment by yamalight** [comment]
Closing this. Feel free to re-open if needed.
