### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by kennetpostigo** [exoframejs/exoframe#286]
Hey,

by any chance is there a community discord server? Would be pretty nice to chat with other users of exoframe and maintainers.

**Comment by yamalight** [comment]
Not strictly exoframe, but there [BxJS discord server](https://discord.gg/hnKCXqQ) where we have quite a few people who use exoframe along with me :)

**Comment by yamalight** [comment]
Closing this. Feel free to re-open if needed.
