### ISSUE TITLE
Saving/persisting containers through docker swarm leave

### ISSUE THREAD

**Issue by kyuumeitai** [exoframejs/exoframe#288]
Hi there, great job!

Wondering if there's some way to save/persist the already deployed images in the case that a docker swarm leave was needed. 

In my case, I added a key in `authorized_keys` and didn't know how to make exoframe-server recognize the keys without recreating the swarm.

Thank you!

**Comment by yamalight** [comment]
So, you've bundled keys into the custom image directly? 🤔 
That's an interesting way of doing it, but I'd suggest using swarm volumes with custom drivers (e.g. NFS) - that way you can update keys without need to change anything but data inside the volume.

**Comment by yamalight** [comment]
Closing this, feel free to re-open if needed.
