### ISSUE TITLE
Can you make a way to control the amount of containers spawned on the Exoframe server?

### ISSUE THREAD

**Issue by Sm03leBr00t** [exoframejs/exoframe#290]
This is just a suggestion, if you have lots of traffic this could be a good thing.

**Comment by yamalight** [comment]
There's a ticket for that: https://github.com/exoframejs/exoframe/issues/125
It should be possible in theory, but I haven't had time to try and implement it 🤔

**Comment by Sm03leBr00t** [comment]
Should I close the issue then :)

**Comment by yamalight** [comment]
If you don't have any follow up questions - yes :)
