### ISSUE TITLE
Allow multiple IDS to be removed

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#291]
Ref: https://github.com/exoframejs/exoframe/blob/568969c73132e644391e21ba8defaf429589b4d8/src/commands/remove.js#L8

**Comment by yamalight** [comment]
That sounds like a pretty dangerous operation that might result in some unwanted removals.
What would be the use case?

**Comment by FDiskas** [comment]
If I have backend and frontend also and database and want to drop that experiment.
Use case:
```
exoframe list
exoframe rm backend frontend db
```

**Comment by yamalight** [comment]
I did some more thinking and think that this is a bad idea to add to core. 
Not only does this significantly increases complexity, it will also require adding confirmations, checks and separate error handling.
I think using shell scripts / pipe for that would be better. Closing this.
