### ISSUE TITLE
Exoframe server has no restart policy after update

### ISSUE THREAD

**Issue by Tiim** [exoframejs/exoframe#295]
First of all, thank you so much for exoframe, it's an amazing project. I saved me a lot of fumbling around with some kind of overkill private docker registry for my single server project.

A few weeks ago I upgraded my exoframe from version around 6.1.0 or 6.0.2 (not sure anymore)
to the newest version. Now a few days ago i rebooted the server and apparently exoframe and traefik didn't start up again, all the deployed containers did. 

A quick inspection of the stopped container showed:
```
$ docker inspect exoframe-server | grep RestartPolicy -A 3
"RestartPolicy": {
    "Name": "",
    "MaximumRetryCount": 0
},
```

When I manually started the docker container with the `--restart always ` flag like shown in the 
documentation then the RestartPolicy looks like this:
```
$ docker inspect 0fc736562fb8 | grep RestartPolicy -A 3
"RestartPolicy": {
  "Name": "always",
  "MaximumRetryCount": 0
},
```

I guess the update didn't properly set the restart flag and therefore the server won't spin up after a crash or a reboot etc.

**Comment by yamalight** [comment]
Yep, that's currently not transferred. Would be a nice improvement.
Here's a relevant bit of code: https://github.com/exoframejs/exoframe-server/blob/master/src/routes/update.js#L77
PRs welcome :)

**Comment by yamalight** [comment]
Should be fixed now. Thanks for PR! ❤️

**Comment by Tiim** [comment]
For future reference since the restart policy is only retained for updates from version `>=6.2.1` the following command will set the restart policy of the exoframe-server container to 'always':

```sh
docker update --restart=always $(docker ps --format {{.Names}} | grep exoframe-server)
```
