### ISSUE TITLE
Exoframe is missing a LICENSE file

### ISSUE THREAD

**Issue by muratg** [exoframejs/exoframe#298]
It says `MIT` in the README, so I assume it is, but just wanted to check before I clone.

(Thanks for the great tooling BTW!)

**Comment by muratg** [comment]
This applies to both this repo, and `exoframe-server` repo. Thanks.

**Comment by yamalight** [comment]
just as READMEs / package.json say - it is indeed MIT licensed :)

**Comment by muratg** [comment]
Cool, I guess that's good enough
