### ISSUE TITLE
Move config file

### ISSUE THREAD

**Issue by ForsakenHarmony** [exoframejs/exoframe#309]
Hey there, would be nice if the config file could be moved to not clutter the home directory

i.e. use the Linux standard of `.config/exoframe`

**Comment by yamalight** [comment]
This is quite a bit of work, but I'd be more than happy to accept a PR that implements reading config folder location from `EXO_CONFIG_PATH` env var (needs to be done in both server and client for consistency) 🤔

**Comment by ForsakenHarmony** [comment]
Would you also be happy with changing the default and automatically migrating things?

It's not really manageable for me to add an environment variable for every single program to use the default location provided by Linux/XDG

Maybe $XDG_CONFIG_HOME could be used https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
though it does default to `$HOME/.config` if it's not defined

**Comment by yamalight** [comment]
Changing defaults with auto-migration would also work!

**Comment by ForsakenHarmony** [comment]
I probably won't get around to this, given that I don't use exoframe right now, sorry

If you're interested in doing this yourself, feel free to, otherwise you're also free to close this to reduce the issue burden

**Comment by yamalight** [comment]
@ForsakenHarmony no worries! already planned it for v7.0 (as a one of breaking changes).

**Comment by yamalight** [comment]
This is done.
