### ISSUE TITLE
docker-compose build and recreate

### ISSUE THREAD

**Issue by FDiskas** [exoframejs/exoframe#315]
I know that this is rare case, but for consistency I would like to have it recreated every time I deploy the app
like
```
docker-compose up --build --force-recreate
```
In my case - I have docker compose it points to docker file and in that docker file is 
```
FROM someperson/some-server:latest
```
and I do not get the latest server version on redeploy.

**Comment by yamalight** [comment]
@FDiskas I'll be removing compose support in the next version as it's a poor fit (see #311 for more detailed reasoning).
I'd recommend either using specific versions of image, or dropping compose completely (as it works poorly with exoframe anyways).

**Comment by FDiskas** [comment]
@Tiim thanks for response. So that means we need to use docker `multi-stage` if we need multiple services?

**Comment by yamalight** [comment]
@FDiskas multi-stage builds won't help here.
what you want to do is to create multiple exoframe deployments (e.g. one for your db, one for the server). I did that for [BxJS website](https://github.com/BuildingXwithJS/BxJS-Website/tree/ai), see [db](https://github.com/BuildingXwithJS/BxJS-Website/tree/ai/hasura/db) and [hasura](https://github.com/BuildingXwithJS/BxJS-Website/tree/ai/hasura) folders.
