### ISSUE TITLE
Broken project config file results in a endless "Uploading project to server..."

### ISSUE THREAD

**Issue by schorsch3000** [exoframejs/exoframe#38]
Hi,
having a broken config-file ( nonvalid json) results in a ~~possible endless~~ 2 minutes spinner with the uploading message, resulting in an Bad Gateway message which results in a JSON parsing error since "Bad Gateway" is not valid JOSN :)
It would be easy to check the config file to be a valid json before uploading.

I would happily provide a PR for this issue, but i'm not 100% sure what the error workflow is.
is it just this:?
```
spinner.fail("Your exoframe.json is not valid");
return;
```

**Comment by yamalight** [comment]
That's a good catch. Would appreciate the PR!

**Comment by yamalight** [comment]
Fix is merged, I still need to add test for it.
