### ISSUE TITLE
Deployment errors should be more explanatory

### ISSUE THREAD

**Issue by FrancosLab** [exoframejs/exoframe#58]
Whenever I try to upload my node app it continuously fails during the upload process

However, it works fine uploading a simple index.html.
Any insight on this? Where can i find the logs for this error

Error: "Error deploying project: HTTPError: Response code 500 (Internal Server Error)"

**Comment by FrancosLab** [comment]
Figured it out, I required Git installed for some of node pages, and alpine does not have it include. 

Simple fix was to create my own Dockerfile based off the current one and simply adding

`RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh`

**Comment by yamalight** [comment]
@FrancosLab thanks for reporting! I definitely should make errors more descriptive. Will do that in one of the next releases! 👍

**Comment by yamalight** [comment]
@FrancosLab can you please tell me the name of the lib you are used to produce this error?

**Comment by yamalight** [comment]
Better errors landed in server 0.16.0: https://github.com/exoframejs/exoframe-server/releases/tag/0.16.0

**Comment by yamalight** [comment]
@FrancosLab I've assembled this test case, please let me know if that's close enough to your case: 
https://github.com/exoframejs/exoframe-server/tree/master/test/fixtures/broken-node-project
