### ISSUE TITLE
Use node:latest base image for node.js projects

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#63]
Alpine node seems to be bringing a bit too many troubles for users.

**Comment by yamalight** [comment]
Done in https://github.com/exoframejs/exoframe-server/commit/02e7fc5e60dff25b24f45568ef45fb4580f1ef4b

**Comment by yamalight** [comment]
Released in https://github.com/exoframejs/exoframe-server/releases/tag/0.18.0

**Comment by airtonix** [comment]
what kind of problems? if it's about dependencies that cause native modules to be compiled, then that's all about `apk --update --no-cache add ...`.

in a continuous deployment scenario, when deploying and choosing between a 300mb and a 5mb base image I know which one I'm choosing.

**Comment by yamalight** [comment]
@airtonix there was a significant number of things breaking for people who just wanted to deploy things with one command, hence the decision to switch back.
You can still use custom Dockerfile with alpine base to make the deployment small (you'd need to do that anyway for custom deps in old scenario).
