### ISSUE TITLE
Successful deployment, but shows error

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#64]
See:
https://cdn.discordapp.com/attachments/358008901834244111/358116706327199745/2017-09-15_080148.jpg

**Comment by surepe** [comment]
After lifting to exoframe latest it's all the same behavior, but another error:

![2017-09-15_215734](https://user-images.githubusercontent.com/30002276/30499032-9eebad24-9a61-11e7-9639-5178088e4833.png)
