### ISSUE TITLE
Better update flow

### ISSUE THREAD

**Issue by yamalight** [exoframejs/exoframe#68]
Currently `exoframe update` command only shows that update is available. We need to ask user if he wants to execute the related update immediately (i.e. if there's update for server and use says "yes" - we execute `exoframe server update`)

**Comment by yamalight** [comment]
Alternatively - we can actually ask user if he wants to execute update immediately

**Comment by EliasJorgensen** [comment]
I can take a look at this 😄

**Comment by yamalight** [comment]
@EliasJorgensen sorry, I just implemented the feature. Planning to release 1.0 next week, need to clean up this stuff
