### ISSUE TITLE
Private keys with passphrase aren't working

### ISSUE THREAD

**Issue by FWeinb** [exoframejs/exoframe#83]
First of all: Thanks for all the effort you put into this. Got it working in no time. 

One problem I encountered was that you can't login (`exoframe login`) with a private key that is secured by a passphrase. After some investigation the culprit might be in [these lines](https://github.com/exoframejs/exoframe/blob/master/src/commands/login.js#L104-L108). In the [docs for jsonwebtoken](https://github.com/auth0/node-jsonwebtoken/blob/master/README.md#jwtsignpayload-secretorprivatekey-options-callback) the passphrase should be passed in conformance of the node crypto api like `{key, passphrase}`. You are passing a `Buffer` object as the key but the [crypto api](https://nodejs.org/api/crypto.html#crypto_sign_sign_privatekey_outputformat) explicitly states that `key` and `passphrase` should be of type `<string>`.

**Comment by yamalight** [comment]
Hi @FWeinb! Thanks for feedback!
Could you please provide a simple test case? Because for I just added a [very basic one](https://github.com/exoframejs/exoframe/commit/006238f6db5ffde39cb415b12826f759f972a51f) and it seems to be working just fine. 
I am also using Exoframe with a key that uses passphrase without issues. Maybe it's not the passphrase that's the problem? 
Can you also please provide meta info about your key?

**Comment by FWeinb** [comment]
Sorry for the wrong report direction. Just noticed that I am using a key in the new OpenSSH format which is no longer in PEM. That might be the problem. 
The key was generated using `ssh-keygen` like this:
```
ssh-keygen -b 4096 -o -a 500 -f ~/.ssh/my_key
```

**Comment by yamalight** [comment]
@FWeinb ah, yes, that's definitely the issue - since node-jsonwebtoken uses node crypto for signing, it only [supports PEM format](https://nodejs.org/api/crypto.html#crypto_sign_sign_privatekey_outputformat) (for now?) 😑

**Comment by FWeinb** [comment]
Thanks for the help. Converted the key into PEM format and everything is working fine.

**Comment by yamalight** [comment]
Cool, glad we were able to solve it so quickly :)

**Comment by airtonix** [comment]
Does the process of creating a compatiable key need to be documented, because I am unable to login.

using your `docker run ...` command in the `README.md` and I get : 

```

docker-rpi master *% = $ exoframe endpoint http://exoframe.dev:8080/
Updating endpoint URL to: http://exoframe.dev:8080/
Endpoint URL updated!
docker-rpi master *% = $ exoframe login
Logging in to: http://exoframe.dev:8080
? Username: admin
? Private key: id_rsa--xps15
! RequestError: connect
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error getting login request phrase. Make sure your endpoint is correct!
RequestError: connect ECONNREFUSED 127.0.0.1:8080
```

**Comment by airtonix** [comment]
Tried it again with another `EXO_PRIVATE_KEY` : 

```

docker-rpi master *% = $ ..\run--exoframe.ps1
ae7758f01ec30943aebfa93d88454ebe4f9be276b195ec9230745ec726e7f611
docker-rpi master *% = $ exoframe endpoint http://exoframe.dev:8080/
Updating endpoint URL to: http://exoframe.dev:8080/
Endpoint URL updated!
docker-rpi master *% = $ exoframe login
Logging in to: http://exoframe.dev:8080
? Username: admin
? Private key: id_rsa--xps15
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error getting login request phrase. Make sure your endpoint is correct! RequestError: connect ECONNREFUSED 127.0.0.1:8080
docker-rpi master *% = $
```

Same result.
