### ISSUE TITLE
Allow specifying additional docker labels via project config

### ISSUE THREAD

**Issue by FWeinb** [exoframejs/exoframe#85]
It would be great to have the ability to change treafik options (e.g. expose via http/https, auto-redirect to https) in the `exoframe.json`. 

It looks like you can override the default behaviour using [container labels](https://docs.traefik.io/configuration/backends/docker/#labels-overriding-default-behaviour). Adding a `Labels` key to the `exoframe.json` and adding these to the container during start would make this possible. 

So disabling https for a specify project would work like this:
###### exoframe.json
```js
Labels: [
  "traefik.frontend.entryPoints=http"
]
```

Left to do:
- [x] Document it (added in https://github.com/exoframejs/exoframe/pull/94)
- [ ] Add client support (in `exoframe config`)

**Comment by yamalight** [comment]
I guess it'd be best to just provide option to set custom labels via exoframe config. Renaming the issue accordingly.
Should be quite easy to implement.

**Comment by yamalight** [comment]
Server support shipped in [v1.1.0](https://github.com/exoframejs/exoframe-server/releases/tag/1.1.0)

**Comment by yamalight** [comment]
Left to do:
- [ ] Add client support (in `exoframe config`)
- [ ] Document it

**Comment by FWeinb** [comment]
Just an aside: How would I update the exoframe-server without having to redeploy everything to my server? I am new to docker and don't know if there is a way to upgrade exoframe-server.

**Comment by yamalight** [comment]
@FWeinb there is `exoframe update server` command for that 😄

**Comment by FWeinb** [comment]
Awesome! Thanks for all your work. Really nice to use it. Makes deploying simple side projects so much easier.

**Comment by yamalight** [comment]
@FWeinb happy to hear you are liking it 😃

**Comment by FWeinb** [comment]
@yamalight Sorry for abusing this thread this much for general questions. No idea where to post these questions. 

But it looks like the latest release is not published to the [docker hub](https://hub.docker.com/r/exoframe/server/tags/) so the server won't get update to the latest version yet.

**Comment by yamalight** [comment]
@FWeinb feel free to open new issues :)

For some reason no new images were pushed from CI, I'll check why that happened in a second 🤔

**Comment by yamalight** [comment]
Cleaned up off-topic a bit.

**Comment by yamalight** [comment]
Done and ready to ship.
