### ISSUE TITLE
exoframe login returns 

### ISSUE THREAD

**Issue by airtonix** [exoframejs/exoframe#92]
I started the server with 

```
docker run -d `
    -v /var/run/docker.sock:/var/run/docker.sock `
    -v /c/Data/Projects/Mine/Exoframe:/root/.exoframe `
    -v /c/Data/Projects/Mine/Exoframe/authorized_keys:/root/.ssh/authorized_keys:ro `
    -e EXO_PRIVATE_KEY=your_private_key `
    --label traefik.backend=exoframe-server `
    --label traefik.frontend.rule=Host:exoframe.dev4.fusion.one `
    --name exoframe-server `
    exoframe/server
```

authorized_keys has the public key of the passwordless private key I choose next:

```

C:\Data\Projects\Mine\Exoframe> exoframe login http://exoframe.dev4.fusion.one
Logging in to: http://localhost:8080
? Username: admin
? Private key: id_rsa.fusion.exoframe
? Private key passpharse (leave blank if not set): [hidden]
Error logging in! Error getting login request phrase. Make sure your endpoint is correct! RequestError: connect ECONNREFUSED 127.0.0.1:8080
```

I'm confused.

- it says `Logging in to: http://localhost:8080`, i'd expect it to say `Logging in to: http://exoframe.dev4.fusion.one`
- error is `RequestError: connect ECONNREFUSED 127.0.0.1:8080` not `RequestError: connect ECONNREFUSED IP_OF_MY_MACHINE`

I know why I'm getting `ECONNREFUSED` since I'm not running anything with port `8080` exposed. (traefik has it exposed on port `80`)

**Comment by airtonix** [comment]
I really want to get this working for our concourse CI system, where we generate kss styleguides, which I see being published to exoframe with `http://<version>.<project>.styleguides.lan` domains.

**Comment by yamalight** [comment]
@airtonix you need to change your endpoint using `exoframe endpoint http://exoframe.dev4.fusion.one` first (see tutorial in the readme). the default endpoint is `localhost:8080`

**Comment by airtonix** [comment]
@yamalight success! thanks for your patience in putting up with my grumpy arse.

**Comment by yamalight** [comment]
glad it worked out!
