### ISSUE TITLE
Updating server occasionally fails with internal error

### ISSUE THREAD

**Issue by FWeinb** [exoframejs/exoframe#96]
Just tried to update to the latest server version (1.1.1) but it fails with:
```
Updating server on: **********
Error updating server: Internal Server Error
Update log:

No log available
```

Would be great to have a way to get the server version (maybe `exoframe endpoint info`) because subsequent calls to `exoframe update server` return `Server is already up to date!` but the server isn't updated.

**Comment by yamalight** [comment]
@FWeinb you should be able to check version using `exoframe update`.
Can you check if it has indeed updated? If yes - I think it's an old bug that breaks connection to client during update causing this error 😭

**Comment by FWeinb** [comment]
Using `exoframe update` worked.

**Comment by yamalight** [comment]
OK, that means that old bug is back. I'll re-open this issue and will try to figure out how to get rid of it for good :)

**Comment by yamalight** [comment]
Hopefully should be [fixed in develop](https://github.com/exoframejs/exoframe-server/commit/d5512b9d9b0dd4510ca68774646e90f32f820fb0) now.
