### ISSUE TITLE
Exoframe login HTTPError: Response code 503

### ISSUE THREAD

**Issue by eryi** [exoframejs/exoframe#98]
I followed the installation instructions for exoframe-server  
1. accessing port 80 shows a "Powered by Exoframe" page
2. ~/.exoframe only contains a traefik directory, server.config.yml was not found

I tried logging in with exoframe-cli
1. ssh login with private key works
2. exoframe login results in
````
Error logging in! Check your username and password and try again. HTTPError: Response code 503 (Service Unavailable)
````

docker logs exoframe-traefik
````
time="2017-12-19T07:52:33Z" level=info msg="Using TOML configuration file /dev/null"
````

docker logs exoframe-server
````
2017-12-19T07:52:32.318Z - info: [exoframe-server] Initializing docker services...
2017-12-19T07:52:32.850Z - info: [exoframe-server] Traefik instance started..
2017-12-19T07:52:32.916Z - info: [exoframe-server] Server running at: http://0.0.0.0:8080

````

**Comment by eryi** [comment]
Found my mistake. Mounted the wrong volumes. Everything works now.

Thanks for the hint!

**Comment by yamalight** [comment]
Ah, great! Glad it was so easy to figure out :)

**Comment by htkoca** [comment]
To add to the solution: Make sure `user` in `/home/user/.ssh/authorized_keys` is replaced with your username
